In [1]:
from google.colab import drive
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
drive_base_dir = '/content/drive/MyDrive/project/autoscout'

In [5]:
drive_data_dir = drive_base_dir+'/data'
drive_model_dir = drive_base_dir+'/model'
drive_plot_dir = drive_base_dir+'/plot'
drive_script_dir = drive_base_dir+'/script'

In [6]:
!jupyter nbconvert --to script '{drive_base_dir}/missing_value_analysis.ipynb'
!mv '{drive_base_dir}/missing_value_analysis.py' '{drive_script_dir}'

[NbConvertApp] Converting notebook /content/drive/MyDrive/project/autoscout/missing_value_analysis.ipynb to script
[NbConvertApp] Writing 22599 bytes to /content/drive/MyDrive/project/autoscout/missing_value_analysis.py

### Dataset import

In [7]:
df = pd.read_csv(drive_data_dir+'/data_clean.csv')

In [8]:
df.head()

,make_model,body_type,vat,registration_month,registration_year,prev_owner,type,next_inspection_month,next_inspection_year,inspection_new,body_color,paint_type,upholstery_texture,upholstery_color,gearing_type,fuel,co2_emission,emission_class,emission_label,drive_chain,consumption_comb,consumption_city,consumption_country,country_version,entertainment_media,safety_security,comfort_convenience,extras,price,km,hp,displacement,warranty,weight,nr_of_doors,nr_of_seats,cylinders,gears,null,kw,full_service,nonsmoking_vehicle,offer_number,model_code,electricity_consumption,other_fuel_types,last_service_date,last_timing_belt_service_date,availability,available_from
0,Audi A1,Sedans,VAT deductible,1.0,2016.0,2.0,Used,6.0,2021.0,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,NaN,Front,3.8,4.3,3.5,NaN,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Catalytic Converter,Voice Control",15770,56013.0,66.0,1422.0,NaN,1220.0,5.0,5.0,3.0,NaN,NaN,NaN,NaN,NaN,LR-062483,0588/BDF,NaN,NaN,NaN,NaN,NaN,NaN
1,Audi A1,Sedans,Price negotiable,3.0,2017.0,NaN,Used,NaN,NaN,NaN,Red,NaN,Cloth,Grey,Automatic,Gasoline,129.0,Euro 6,4.0,Front,5.6,7.1,4.7,NaN,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Central door lock with r...","Air conditioning,Automatic climate control,Hil...","Alloy wheels,Sport seats,Sport suspension,Voic...",14500,80000.0,141.0,1798.0,NaN,1255.0,3.0,4.0,4.0,7.0,NaN,NaN,NaN,NaN,NaN,0588/BCY,NaN,NaN,NaN,NaN,NaN,NaN
2,Audi A1,Sedans,VAT deductible,2.0,2016.0,1.0,Used,NaN,NaN,NaN,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.4,3.4,NaN,"MP3,On-board computer","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Cruise control,Electrical sid...","Alloy wheels,Voice Control",14640,83450.0,85.0,1598.0,NaN,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,AM-95365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Audi A1,Sedans,NaN,8.0,2016.0,1.0,Used,NaN,NaN,NaN,Brown,Metallic,NaN,NaN,Automatic,Diesel,99.0,Euro 6,NaN,NaN,3.8,4.3,3.5,NaN,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Alarm system,Central door lock with remote...","Air suspension,Armrest,Auxiliary heating,Elect...","Alloy wheels,Sport seats,Voice Control",14500,73000.0,66.0,1422.0,NaN,1195.0,3.0,4.0,3.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Audi A1,Sedans,NaN,5.0,2016.0,1.0,Used,NaN,NaN,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,109.0,Euro 6,NaN,Front,4.1,4.6,3.8,Germany,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Central door lock,Driver-side airbag,Elect...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Sport package,Sport suspension,Vo...",16790,16200.0,66.0,1422.0,NaN,NaN,5.0,5.0,3.0,NaN,NaN,NaN,NaN,NaN,C1626,0588/BDF,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   make_model                     15919 non-null  object
 1   body_type                      15859 non-null  object
 2   vat                            11406 non-null  object
 3   registration_month             14322 non-null  float64
 4   registration_year              14322 non-null  float64
 5   prev_owner                     9116 non-null   float64
 6   type                           15917 non-null  object
 7   next_inspection_month          2825 non-null   float64
 8   next_inspection_year           2825 non-null   float64
 9   inspection_new                 3570 non-null   object
 10  body_color                     15322 non-null  object
 11  paint_type                     10147 non-null  object
 12  upholstery_texture             11416 non-null  object
 13  upholstery_color               10897 non-null  object
 14  gearing_type                   15919 non-null  object
 15  fuel                           15919 non-null  object
 16  co2_emission                   13483 non-null  float64
 17  emission_class                 12291 non-null  object
 18  emission_label                 3945 non-null   float64
 19  drive_chain                    9061 non-null   object
 20  consumption_comb               13886 non-null  float64
 21  consumption_city               13483 non-null  float64
 22  consumption_country            13543 non-null  float64
 23  country_version                7586 non-null   object
 24  entertainment_media            14545 non-null  object
 25  safety_security                14937 non-null  object
 26  comfort_convenience            14999 non-null  object
 27  extras                         12957 non-null  object
 28  price                          15919 non-null  int64
 29  km                             14895 non-null  float64
 30  hp                             15831 non-null  float64
 31  displacement                   15423 non-null  float64
 32  warranty                       4853 non-null   float64
 33  weight                         8945 non-null   float64
 34  nr_of_doors                    15707 non-null  float64
 35  nr_of_seats                    14942 non-null  float64
 36  cylinders                      10239 non-null  float64
 37  gears                          11207 non-null  float64
 38  null                           0 non-null      float64
 39  kw                             0 non-null      float64
 40  full_service                   0 non-null      float64
 41  nonsmoking_vehicle             0 non-null      float64
 42  offer_number                   12744 non-null  object
 43  model_code                     4978 non-null   object
 44  electricity_consumption        0 non-null      float64
 45  other_fuel_types               0 non-null      float64
 46  last_service_date              506 non-null    object
 47  last_timing_belt_service_date  16 non-null     object
 48  availability                   635 non-null    float64
 49  available_from                 272 non-null    object
dtypes: float64(26), int64(1), object(23)
memory usage: 6.1+ MB

### Missing value count

In [10]:
df.isnull().sum()*100 / df.shape[0]

make_model                         0.000000
body_type                          0.376908
vat                               28.349771
registration_month                10.032037
registration_year                 10.032037
prev_owner                        42.735096
type                               0.012564
next_inspection_month             82.253910
next_inspection_year              82.253910
inspection_new                    77.573968
body_color                         3.750236
paint_type                        36.258559
upholstery_texture                28.286953
upholstery_color                  31.547208
gearing_type                       0.000000
fuel                               0.000000
co2_emission                      15.302469
emission_class                    22.790376
emission_label                    75.218293
drive_chain                       43.080596
consumption_comb                  12.770903
consumption_city                  15.302469
consumption_country               14.925561
country_version                   52.346253
entertainment_media                8.631195
safety_security                    6.168729
comfort_convenience                5.779257
extras                            18.606696
price                              0.000000
km                                 6.432565
hp                                 0.552799
displacement                       3.115774
warranty                          69.514417
weight                            43.809285
nr_of_doors                        1.331742
nr_of_seats                        6.137320
cylinders                         35.680633
gears                             29.599849
null                             100.000000
kw                               100.000000
full_service                     100.000000
nonsmoking_vehicle               100.000000
offer_number                      19.944720
model_code                        68.729192
electricity_consumption          100.000000
other_fuel_types                 100.000000
last_service_date                 96.821408
last_timing_belt_service_date     99.899491
availability                      96.011056
available_from                    98.291350
dtype: float64

In [11]:
drop_col = ['registration_month', 'next_inspection_month', 'next_inspection_year', 'null', 'kw', 'full_service', 'nonsmoking_vehicle', 'offer_number', 'model_code', 'electricity_consumption', 'other_fuel_types', 'last_service_date', 'last_timing_belt_service_date', 'availability', 'available_from']

In [12]:
df.drop(drop_col, axis=1, inplace=True)

In [13]:
df.head()

,make_model,body_type,vat,registration_year,prev_owner,type,inspection_new,body_color,paint_type,upholstery_texture,upholstery_color,gearing_type,fuel,co2_emission,emission_class,emission_label,drive_chain,consumption_comb,consumption_city,consumption_country,country_version,entertainment_media,safety_security,comfort_convenience,extras,price,km,hp,displacement,warranty,weight,nr_of_doors,nr_of_seats,cylinders,gears
0,Audi A1,Sedans,VAT deductible,2016.0,2.0,Used,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,NaN,Front,3.8,4.3,3.5,NaN,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Catalytic Converter,Voice Control",15770,56013.0,66.0,1422.0,NaN,1220.0,5.0,5.0,3.0,NaN
1,Audi A1,Sedans,Price negotiable,2017.0,NaN,Used,NaN,Red,NaN,Cloth,Grey,Automatic,Gasoline,129.0,Euro 6,4.0,Front,5.6,7.1,4.7,NaN,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Central door lock with r...","Air conditioning,Automatic climate control,Hil...","Alloy wheels,Sport seats,Sport suspension,Voic...",14500,80000.0,141.0,1798.0,NaN,1255.0,3.0,4.0,4.0,7.0
2,Audi A1,Sedans,VAT deductible,2016.0,1.0,Used,NaN,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.4,3.4,NaN,"MP3,On-board computer","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Cruise control,Electrical sid...","Alloy wheels,Voice Control",14640,83450.0,85.0,1598.0,NaN,NaN,4.0,4.0,NaN,NaN
3,Audi A1,Sedans,NaN,2016.0,1.0,Used,NaN,Brown,Metallic,NaN,NaN,Automatic,Diesel,99.0,Euro 6,NaN,NaN,3.8,4.3,3.5,NaN,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Alarm system,Central door lock with remote...","Air suspension,Armrest,Auxiliary heating,Elect...","Alloy wheels,Sport seats,Voice Control",14500,73000.0,66.0,1422.0,NaN,1195.0,3.0,4.0,3.0,6.0
4,Audi A1,Sedans,NaN,2016.0,1.0,Used,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,109.0,Euro 6,NaN,Front,4.1,4.6,3.8,Germany,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Central door lock,Driver-side airbag,Elect...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Sport package,Sport suspension,Vo...",16790,16200.0,66.0,1422.0,NaN,NaN,5.0,5.0,3.0,NaN

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   make_model           15919 non-null  object
 1   body_type            15859 non-null  object
 2   vat                  11406 non-null  object
 3   registration_year    14322 non-null  float64
 4   prev_owner           9116 non-null   float64
 5   type                 15917 non-null  object
 6   inspection_new       3570 non-null   object
 7   body_color           15322 non-null  object
 8   paint_type           10147 non-null  object
 9   upholstery_texture   11416 non-null  object
 10  upholstery_color     10897 non-null  object
 11  gearing_type         15919 non-null  object
 12  fuel                 15919 non-null  object
 13  co2_emission         13483 non-null  float64
 14  emission_class       12291 non-null  object
 15  emission_label       3945 non-null   float64
 16  drive_chain          9061 non-null   object
 17  consumption_comb     13886 non-null  float64
 18  consumption_city     13483 non-null  float64
 19  consumption_country  13543 non-null  float64
 20  country_version      7586 non-null   object
 21  entertainment_media  14545 non-null  object
 22  safety_security      14937 non-null  object
 23  comfort_convenience  14999 non-null  object
 24  extras               12957 non-null  object
 25  price                15919 non-null  int64
 26  km                   14895 non-null  float64
 27  hp                   15831 non-null  float64
 28  displacement         15423 non-null  float64
 29  warranty             4853 non-null   float64
 30  weight               8945 non-null   float64
 31  nr_of_doors          15707 non-null  float64
 32  nr_of_seats          14942 non-null  float64
 33  cylinders            10239 non-null  float64
 34  gears                11207 non-null  float64
dtypes: float64(16), int64(1), object(18)
memory usage: 4.3+ MB

In [15]:
df.isnull().sum()*100 / df.shape[0]

make_model              0.000000
body_type               0.376908
vat                    28.349771
registration_year      10.032037
prev_owner             42.735096
type                    0.012564
inspection_new         77.573968
body_color              3.750236
paint_type             36.258559
upholstery_texture     28.286953
upholstery_color       31.547208
gearing_type            0.000000
fuel                    0.000000
co2_emission           15.302469
emission_class         22.790376
emission_label         75.218293
drive_chain            43.080596
consumption_comb       12.770903
consumption_city       15.302469
consumption_country    14.925561
country_version        52.346253
entertainment_media     8.631195
safety_security         6.168729
comfort_convenience     5.779257
extras                 18.606696
price                   0.000000
km                      6.432565
hp                      0.552799
displacement            3.115774
warranty               69.514417
weight                 43.809285
nr_of_doors             1.331742
nr_of_seats             6.137320
cylinders              35.680633
gears                  29.599849
dtype: float64

In [16]:
df.columns

Index(['make_model', 'body_type', 'vat', 'registration_year', 'prev_owner',
       'type', 'inspection_new', 'body_color', 'paint_type',
       'upholstery_texture', 'upholstery_color', 'gearing_type', 'fuel',
       'co2_emission', 'emission_class', 'emission_label', 'drive_chain',
       'consumption_comb', 'consumption_city', 'consumption_country',
       'country_version', 'entertainment_media', 'safety_security',
       'comfort_convenience', 'extras', 'price', 'km', 'hp', 'displacement',
       'warranty', 'weight', 'nr_of_doors', 'nr_of_seats', 'cylinders',
       'gears'],
      dtype='object')

### Helper Function

In [17]:
def fill_one_stage(df, group_col, target_col, method):
    df_fill = df.copy()

    supported_methods = ['mean', 'median', 'mode', 'ffill', 'bfill']

    if method not in supported_methods:
        raise ValueError(f"Method '{method}' not supported. Choose from: {', '.join(supported_methods)}")

    nan_count_initial = df_fill[target_col].isnull().sum()

    if method == 'mode':
        fill_value = df_fill.groupby(group_col)[target_col].transform(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
        df_fill[target_col] = df_fill[target_col].fillna(fill_value)

    elif method in ['mean', 'median']:
        fill_value = df_fill.groupby(group_col)[target_col].transform(method)
        df_fill[target_col] = df_fill[target_col].fillna(fill_value)

    elif method == 'ffill':
        df_fill[target_col] = df_fill.groupby(group_col)[target_col].transform(lambda x: x.ffill().bfill())

    elif method == 'bfill':
        df_fill[target_col] = df_fill.groupby(group_col)[target_col].transform(lambda x: x.bfill().ffill())

    nan_count_after_group = df_fill[target_col].isnull().sum()

    if nan_count_after_group > 0:

        if method == 'mode':
            fill_value_globe = df_fill[target_col].mode().iloc[0] if not df_fill[target_col].mode().empty else np.nan
            df_fill[target_col] = df_fill[target_col].fillna(fill_value_globe)

        elif method == 'mean':
            fill_value_globe = df_fill[target_col].mean()
            df_fill[target_col] = df_fill[target_col].fillna(fill_value_globe)

        elif method == 'median':
            fill_value_globe = df_fill[target_col].median()
            df_fill[target_col] = df_fill[target_col].fillna(fill_value_globe)

        elif method == 'ffill':
            df_fill[target_col].ffill(inplace=True)
            df_fill[target_col].bfill(inplace=True)

        elif method == 'bfill':
            df_fill[target_col].bfill(inplace=True)
            df_fill[target_col].ffill(inplace=True)

    nan_count_final = df_fill[target_col].isnull().sum()

    return df_fill

In [18]:
def fill_one_stage_iterative(df, group_col, target_col, method):
    df_fill = df.copy()

    supported_methods = ['mean', 'median', 'mode', 'ffill', 'bfill']

    if method not in supported_methods:
        raise ValueError(f"Method '{method}' not supported. Choose from: {', '.join(supported_methods)}")

    nan_count_initial = df_fill[target_col].isnull().sum()

    def get_fill_value(series, method_str):
        if series.empty or series.isnull().all():
            return np.nan

        if method_str == 'mode':
            modes = series.mode()
            return modes.iloc[0]
        elif method_str == 'mean':
            return series.mean()
        elif method_str == 'median':
            return series.median()

        return np.nan


    for group in df_fill[group_col].unique():
        cond = df_fill[group_col] == group
        df_group = df_fill.loc[cond, target_col]

        if method in ['mean', 'median', 'mode']:
            fill_value = get_fill_value(df_group, method)
            if not pd.isna(fill_value):
                df_fill.loc[cond, target_col] = df_group.fillna(fill_value)
        elif method == 'ffill':
            df_fill.loc[cond, target_col] = df_group.ffill().bfill()
        elif method == 'bfill':
            df_fill.loc[cond, target_col] = df_group.bfill().ffill()

    nan_count_after_group = df_fill[target_col].isnull().sum()

    if nan_count_after_group > 0:

        if method in ['mean', 'median', 'mode']:
            fill_value_globe = get_fill_value(df_fill[target_col], method)
            if not pd.isna(fill_value_globe):
                df_fill[target_col] = df_fill[target_col].fillna(fill_value_globe)

        elif method == 'ffill':
           df_fill[target_col].ffill(inplace=True)
           df_fill[target_col].bfill(inplace=True)

        elif method == 'bfill':
           df_fill[target_col].bfill(inplace=True)
           df_fill[target_col].ffill(inplace=True)

    nan_count_final = df_fill[target_col].isnull().sum()

    return df_fill

In [19]:
def fill_two_stage(df, group_col1, group_col2, target_col, method):
    df_fill = df.copy()

    supported_methods = ['mean', 'median', 'mode', 'ffill', 'bfill']
    if method not in supported_methods:
        raise ValueError(f"Method '{method}' not supported. Choose from: {', '.join(supported_methods)}")

    nan_count_initial = df_fill[target_col].isnull().sum()

    if method == 'mode':
        fill_value = df_fill.groupby([group_col1, group_col2])[target_col].transform(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
        df_fill[target_col] = df_fill[target_col].fillna(fill_value)
    elif method in ['mean', 'median']:
        fill_value = df_fill.groupby([group_col1, group_col2])[target_col].transform(method)
        df_fill[target_col] = df_fill[target_col].fillna(fill_value)
    elif method == 'ffill':
        df_fill[target_col] = df_fill.groupby([group_col1, group_col2])[target_col].transform(lambda x: x.ffill().bfill())
    elif method == 'bfill':
        df_fill[target_col] = df_fill.groupby([group_col1, group_col2])[target_col].transform(lambda x: x.bfill().ffill())

    nan_count_level1 = df_fill[target_col].isnull().sum()

    if nan_count_level1 > 0:
        if method == 'mode':
            fill_value_group = df_fill.groupby(group_col1)[target_col].transform(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
            df_fill[target_col] = df_fill[target_col].fillna(fill_value_group)
        elif method in ['mean', 'median']:
            fill_value_group = df_fill.groupby(group_col1)[target_col].transform(method)
            df_fill[target_col] = df_fill[target_col].fillna(fill_value_group)
        elif method == 'ffill':
            df_fill[target_col] = df_fill.groupby(group_col1)[target_col].transform(lambda x: x.ffill().bfill())
        elif method == 'bfill':
            df_fill[target_col] = df_fill.groupby(group_col1)[target_col].transform(lambda x: x.bfill().ffill())

    nan_count_level2 = df_fill[target_col].isnull().sum()

    if nan_count_level2 > 0:
        if method == 'mode':
            fill_value_globe = df_fill[target_col].mode().iloc[0] if not df_fill[target_col].mode().empty else np.nan
            df_fill[target_col] = df_fill[target_col].fillna(fill_value_globe)

        elif method == 'mean':
            fill_value_globe = df_fill[target_col].mean()
            df_fill[target_col] = df_fill[target_col].fillna(fill_value_globe)

        elif method == 'median':
            fill_value_globe = df_fill[target_col].median()
            df_fill[target_col] = df_fill[target_col].fillna(fill_value_globe)

        elif method == 'ffill':
            df_fill[target_col].ffill(inplace=True)
            df_fill[target_col].bfill(inplace=True)

        elif method == 'bfill':
            df_fill[target_col].bfill(inplace=True)
            df_fill[target_col].ffill(inplace=True)

    nan_count_final = df_fill[target_col].isnull().sum()

    return df_fill

In [20]:
def fill_two_stage_iterative(df, group_col1, group_col2, target_col, method):
    df_fill = df.copy()

    supported_methods = ['mean', 'median', 'mode', 'ffill', 'bfill']
    if method not in supported_methods:
        raise ValueError(f"Method '{method}' not supported. Choose from: {', '.join(supported_methods)}")

    nan_count_initial = df_fill[target_col].isnull().sum()

    def get_fill_value(series, method_str):

        if series.empty or series.isnull().all():
            return np.nan

        if method_str == 'mode':
            modes = series.mode()
            return modes.iloc[0] if not modes.empty else np.nan
        elif method_str == 'mean':
            return series.mean()
        elif method_str == 'median':
            return series.median()

        return np.nan


    for group1 in df_fill[group_col1].unique():
        for group2 in df_fill[group_col2].unique():
            cond_level1 = (df_fill[group_col1] == group1) & (df_fill[group_col2] == group2)

            if cond_level1.any():
                if method in ['mean', 'median', 'mode']:
                    group_series_level1 = df_fill.loc[cond_level1, target_col]
                    fill_value = get_fill_value(group_series_level1, method)
                    if not pd.isna(fill_value):
                        df_fill.loc[cond_level1, target_col].fillna(fill_value, inplace=True)
                elif method == 'ffill':
                    df_fill.loc[cond_level1, target_col] = df_fill.loc[cond_level1, target_col].ffill().bfill()
                elif method == 'bfill':
                    df_fill.loc[cond_level1, target_col] = df_fill.loc[cond_level1, target_col].bfill().ffill()

    nan_count_level1 = df_fill[target_col].isnull().sum()

    if nan_count_level1 > 0:
        for group1 in df_fill[group_col1].unique():
            cond_level2 = df_fill[group_col1] == group1

            if cond_level2.any():
                if method in ['mean', 'median', 'mode']:
                    group_series_level2 = df_fill.loc[cond_level2, target_col]
                    fill_value_group = get_fill_value(group_series_level2, method)
                    if not pd.isna(group_series_level2):
                        df_fill.loc[cond_level2, target_col].fillna(fill_value_group, inplace=True)
                elif method == 'ffill':
                    df_fill.loc[cond_level2, target_col] = df_fill.loc[cond_level2, target_col].ffill().bfill()
                elif method == 'bfill':
                    df_fill.loc[cond_level2, target_col] = df_fill.loc[cond_level2, target_col].bfill().ffill()

    nan_count_level2 = df_fill[target_col].isnull().sum()

    if nan_count_level2 > 0:
        if method in ['mean', 'median', 'mode']:
            fill_value_globe = get_fill_value(df_fill[target_col], method)
            if not pd.isna(fill_value_globe):
                df_fill[target_col].fillna(fill_value_globe, inplace=True)
        elif method == 'ffill':
            df_fill[target_col].ffill(inplace=True)
            df_fill[target_col].bfill(inplace=True)
        elif method == 'bfill':
            df_fill[target_col].bfill(inplace=True)
            df_fill[target_col].ffill(inplace=True)

    nan_count_final = df_fill[target_col].isnull().sum()

    return df_fill

### Missing value imputation

#### Column: make_model

In [21]:
df['make_model'].value_counts(dropna=False)

make_model
Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: count, dtype: int64

#### Column: body_type

In [22]:
df['body_type'].value_counts(dropna=False)

body_type
Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: count, dtype: int64

In [23]:
df.groupby(['make_model'])['body_type'].value_counts(dropna=False)

make_model      body_type
Audi A1         Sedans           1538
                Compact          1039
                Station wagon      21
                Other              13
                Coupe               2
                Van                 1
Audi A2         Off-Road            1
Audi A3         Sedans           2598
                Station wagon     282
                Compact           182
                Other              16
                Convertible         8
                NaN                 7
                Coupe               4
Opel Astra      Station wagon    1211
                Sedans           1053
                Compact           185
                Other              67
                NaN                 7
                Coupe               2
                Off-Road            1
Opel Corsa      Compact          1230
                Sedans            875
                Other              87
                Coupe              13
                Transporter         7
                Off-Road            3
                Van                 2
                NaN                 2
Opel Insignia   Station wagon    1611
                Sedans            900
                Other              48
                Compact            27
                Off-Road            7
                NaN                 3
                Coupe               1
                Van                 1
Renault Clio    Sedans            918
                Compact           484
                Station wagon     337
                Other              51
                Transporter        29
                NaN                15
                Off-Road            2
                Van                 2
                Coupe               1
Renault Duster  Off-Road           34
Renault Espace  Van               777
                Station wagon      91
                Transporter        52
                NaN                26
                Sedans             21
                Off-Road            8
                Other               8
                Compact             6
                Coupe               2
Name: count, dtype: int64

In [24]:
df_tmp = fill_one_stage(df, 'make_model', 'body_type', 'mode')
df['body_type'] = df_tmp['body_type']

#### Column: type

In [25]:
df['type'].value_counts(dropna=False)

type
Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: count, dtype: int64

In [26]:
df.groupby(['make_model'])['type'].value_counts(dropna=False)

make_model      type
Audi A1         Used              1808
                New                328
                Employee's car     197
                Pre-registered     146
                Demonstration      135
Audi A2         Employee's car       1
Audi A3         Used              2179
                New                326
                Pre-registered     300
                Employee's car     228
                Demonstration       62
                NaN                  2
Opel Astra      Used              1829
                New                255
                Demonstration      165
                Employee's car     152
                Pre-registered     125
Opel Corsa      Used              1461
                Pre-registered     365
                New                155
                Employee's car     149
                Demonstration       89
Opel Insignia   Used              1840
                New                369
                Demonstration      172
                Employee's car     149
                Pre-registered      68
Renault Clio    Used              1310
                Pre-registered     227
                New                129
                Employee's car      97
                Demonstration       76
Renault Duster  New                 18
                Used                16
Renault Espace  Used               653
                Pre-registered     133
                Demonstration       97
                New                 70
                Employee's car      38
Name: count, dtype: int64

In [27]:
df_tmp = fill_one_stage(df, 'make_model', 'type', 'mode')
df['type'] = df_tmp['type']

#### Column: registration_year

In [28]:
df['registration_year'].value_counts(dropna=False)

registration_year
2018.0    4522
2016.0    3674
2017.0    3273
2019.0    2853
NaN       1597
Name: count, dtype: int64

In [29]:
df.groupby('type')['registration_year'].value_counts(dropna=False)

type            registration_year
Demonstration   2019.0                632
                2018.0                130
                2017.0                 27
                NaN                     5
                2016.0                  2
Employee's car  2018.0                765
                2019.0                127
                2017.0                 99
                2016.0                 17
                NaN                     3
New             NaN                  1547
                2019.0                100
                2018.0                  3
Pre-registered  2019.0               1187
                2018.0                161
                2017.0                  9
                NaN                     6
                2016.0                  1
Used            2016.0               3654
                2018.0               3463
                2017.0               3138
                2019.0                807
                NaN                    36
Name: count, dtype: int64

In [30]:
df_tmp = fill_one_stage(df, 'type', 'registration_year', 'mode')
df['registration_year'] = df_tmp['registration_year']

#### Add column: age

In [31]:
df['age'] = 2019 - df['registration_year']
df['age'].value_counts(dropna=False)

age
1.0    4525
0.0    4411
3.0    3710
2.0    3273
Name: count, dtype: int64

#### Column: prev_owner

In [32]:
df['prev_owner'].value_counts(dropna=False)

prev_owner
1.0    8294
NaN    6803
2.0     778
0.0      25
3.0      17
4.0       2
Name: count, dtype: int64

In [33]:
df.groupby(['type', 'age'])['prev_owner'].value_counts(dropna=False)

type            age  prev_owner
Demonstration   0.0  1.0            394
                     NaN            242
                     2.0              1
                1.0  1.0             94
                     NaN             34
                     2.0              2
                2.0  1.0             19
                     NaN              5
                     2.0              3
                3.0  1.0              1
                     NaN              1
Employee's car  0.0  1.0             72
                     NaN             54
                     2.0              1
                1.0  1.0            532
                     NaN            227
                     2.0              9
                2.0  NaN             71
                     1.0             28
                3.0  1.0              9
                     NaN              8
New             0.0  NaN           1608
                     0.0             25
                     1.0             14
                1.0  NaN              2
                     1.0              1
Pre-registered  0.0  1.0            734
                     NaN            454
                     2.0              5
                1.0  1.0             98
                     NaN             62
                     2.0              1
                2.0  1.0              6
                     NaN              3
                3.0  1.0              1
Used            0.0  NaN            433
                     1.0            371
                     2.0              3
                1.0  1.0           2243
                     NaN           1157
                     2.0             63
                2.0  1.0           1658
                     NaN           1179
                     2.0            293
                     3.0              7
                     4.0              1
                3.0  1.0           2019
                     NaN           1263
                     2.0            397
                     3.0             10
                     4.0              1
Name: count, dtype: int64

In [34]:
df_tmp = fill_two_stage(df, 'type', 'age', 'prev_owner', 'mode')
df['prev_owner'] = df_tmp['prev_owner']

#### Column: km

In [35]:
df['km'].isnull().groupby([df['type'], df['age']]).sum()

type            age
Demonstration   0.0     33
                1.0      0
                2.0      0
                3.0      0
Employee's car  0.0      6
                1.0      2
                2.0      0
                3.0      0
New             0.0    848
                1.0      1
Pre-registered  0.0     91
                1.0     27
                2.0      0
                3.0      0
Used            0.0      4
                1.0      9
                2.0      1
                3.0      2
Name: km, dtype: int64

In [36]:
df['km'].describe()

count     14895.000000
mean      34130.127828
std       37352.977568
min           0.000000
25%        5153.000000
50%       22740.000000
75%       49371.500000
max      317000.000000
Name: km, dtype: float64

In [37]:
df.groupby(['type', 'age'])['km'].mean()

type            age
Demonstration   0.0     3373.867550
                1.0     8294.200000
                2.0    25327.296296
                3.0    45500.000000
Employee's car  0.0     4473.933884
                1.0    19295.278068
                2.0    37926.505051
                3.0    59123.647059
New             0.0       16.987484
                1.0       53.500000
Pre-registered  0.0      100.648820
                1.0      435.514925
                2.0     1854.000000
                3.0       10.000000
Used            0.0     3712.170610
                1.0    18807.503474
                2.0    42131.628626
                3.0    77030.217191
Name: km, dtype: float64

In [38]:
df_tmp = fill_two_stage(df, 'type', 'age', 'km', 'mean')
df['km'] = df_tmp['km']

#### Column: vat

In [39]:
df['vat'].value_counts(dropna=False)

vat
VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: count, dtype: int64

In [40]:
df['vat'] = df['vat'].fillna('Missing')
df['vat'].value_counts(dropna=False)

vat
VAT deductible      10980
Missing              4513
Price negotiable      426
Name: count, dtype: int64

#### Column: warranty

In [41]:
df['warranty'].describe()

count    4853.000000
mean       21.927261
std        15.771120
min         1.000000
25%        12.000000
50%        12.000000
75%        24.000000
max        72.000000
Name: warranty, dtype: float64

In [42]:
df['warranty'] = df['warranty'].fillna(0)
df['warranty'].describe()

count    15919.000000
mean         6.684654
std         13.330917
min          0.000000
25%          0.000000
50%          0.000000
75%         12.000000
max         72.000000
Name: warranty, dtype: float64

#### Column: inspection_new

In [43]:
df['inspection_new'].value_counts(dropna=False)

inspection_new
NaN    12349
Yes     3570
Name: count, dtype: int64

In [44]:
df['inspection_new'] = df['inspection_new'].fillna('No')
df['inspection_new'].value_counts(dropna=False)

inspection_new
No     12349
Yes     3570
Name: count, dtype: int64

#### Column: body_color

In [45]:
df['body_color'].value_counts(dropna=False)

body_color
Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
NaN        597
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: count, dtype: int64

In [46]:
df.groupby(['make_model', 'body_type'])['body_color'].value_counts(dropna=False)

make_model      body_type      body_color
Audi A1         Compact        Black         320
                               White         274
                               Grey          126
                               Blue           96
                               Red            89
                               NaN            44
                               Silver         42
                               Green          17
                               Yellow         16
                               Brown           9
                               Beige           6
                Coupe          Black           2
                Other          White           5
                               Black           4
                               Grey            3
                               Blue            1
                Sedans         White         440
                               Black         384
                               Grey          197
                               Blue          184
                               Red           161
                               Silver         87
                               NaN            29
                               Green          15
                               Yellow         15
                               Brown          13
                               Beige          11
                               Violet          2
                Station wagon  White           8
                               Black           6
                               Blue            5
                               Grey            1
                               Silver          1
                Van            Black           1
Audi A2         Off-Road       Grey            1
Audi A3         Compact        Black          59
                               Grey           41
                               White          29
                               Blue           23
                               Red            18
                               Silver          5
                               NaN             5
                               Brown           2
                Convertible    White           3
                               Red             2
                               Black           1
                               Blue            1
                               Grey            1
                Coupe          Silver          4
                Other          Black           4
                               Blue            4
                               Grey            4
                               White           3
                               NaN             1
                Sedans         Black         768
                               Grey          629
                               White         592
                               Silver        263
                               Blue          187
                               Red            82
                               NaN            60
                               Brown          20
                               Bronze          2
                               Yellow          2
                Station wagon  Black         106
                               White          65
                               Grey           46
                               Silver         25
                               Blue           20
                               NaN             7
                               Red             6
                               Brown           3
                               Yellow          2
                               Orange          1
                               Violet          1
Opel Astra      Compact        Grey           46
                               Black          36
                               White          31
                               Red            24
                               Silver         14
                               Blue           11
                               Brown          11
                               NaN            10
                               Beige           1
                               Green           1
                Coupe          Blue            1
                               Red             1
                Off-Road       Silver          1
                Other          Grey           24
                               Silver         11
                               Black           9
                               White           9
                               Blue            6
                               Red             4
                               NaN             2
                               Brown           1
                               Green           1
                Sedans         Grey          223
                               Silver        184
                               Black         179
                               White         145
                               Blue          100
                               Red            80
                               Brown          67
                               NaN            52
                               Green          16
                               Beige           6
                               Violet          1
                Station wagon  Black         326
                               Grey          247
                               Silver        223
                               White         129
                               Blue          108
                               NaN            75
                               Brown          49
                               Green          31
                               Red            23
                               Beige           6
                               Gold            1
Opel Corsa      Compact        Grey          255
                               White         251
                               Blue          247
                               Black         197
                               Silver        134
                               Red           109
                               NaN            19
                               Green          17
                               Yellow          2
                               Orange          1
                Coupe          Grey            5
                               Red             4
                               White           2
                               Blue            1
                               Silver          1
                Off-Road       Blue            1
                               Grey            1
                               Silver          1
                Other          Grey           21
                               Blue           19
                               Silver         16
                               White          13
                               Black          12
                               Red             5
                               Green           1
                Sedans         Grey          221
                               White         214
                               Silver        131
                               Black         125
                               Blue          114
                               Red            48
                               NaN             9
                               Green           6
                               Brown           3
                               Yellow          2
                               Bronze          1
                               Gold            1
                Transporter    Red             3
                               White           3
                               Blue            1
                Van            White           2
Opel Insignia   Compact        White           8
                               Black           6
                               Blue            6
                               Grey            4
                               Silver          2
                               NaN             1
                Coupe          NaN             1
                Off-Road       NaN             4
                               Green           1
                               Grey            1
                               White           1
                Other          Grey           11
                               Black           9
                               Silver          9
                               Blue            7
                               NaN             6
                               White           4
                               Brown           2
                Sedans         Grey          211
                               Black         185
                               Silver        123
                               White         110
                               NaN           103
                               Blue           94
                               Brown          32
                               Red            26
                               Green          14
                               Beige           1
                               Orange          1
                Station wagon  Grey          464
                               Black         408
                               Silver        243
                               White         184
                               Blue          116
                               NaN           103
                               Green          34
                               Brown          33
                               Red            17
                               Beige          11
                               Bronze          1
                Van            Grey            1
Renault Clio    Compact        White         164
                               Grey           87
                               Red            87
                               Black          78
                               NaN            24
                               Blue           23
                               Silver         17
                               Yellow          4
                Coupe          White           1
                Off-Road       Grey            1
                               White           1
                Other          White          16
                               Black          14
                               Grey            6
                               Red             5
                               Silver          5
                               Blue            3
                               Beige           1
                               Brown           1
                Sedans         White         373
                               Black         167
                               Grey          166
                               Red           125
                               Silver         42
                               Blue           29
                               Beige          15
                               Yellow          8
                               NaN             7
                               Brown           1
                Station wagon  Grey          112
                               Black          72
                               White          63
                               Red            38
                               Silver         18
                               NaN            13
                               Beige          10
                               Blue           10
                               Brown           1
                Transporter    White          25
                               Grey            2
                               NaN             2
                Van            White           2
Renault Duster  Off-Road       White          26
                               Black           8
Renault Espace  Compact        Grey            3
                               Black           2
                               White           1
                Coupe          NaN             2
                Off-Road       Black           5
                               Blue            1
                               Grey            1
                               Silver          1
                Other          Black           4
                               Grey            2
                               White           2
                Sedans         Black           9
                               Grey            5
                               White           3
                               NaN             2
                               Beige           1
                               Silver          1
                Station wagon  Black          24
                               White          22
                               Grey           20
                               Brown          10
                               Beige           9
                               Silver          2
                               Violet          2
                               NaN             2
                Transporter    Grey           17
                               Black          13
                               White           9
                               Silver          5
                               Brown           4
                               Beige           3
                               Violet          1
                Van            Grey          299
                               Black         202
                               White         173
                               Silver         36
                               Beige          27
                               Brown          27
                               NaN            14
                               Blue           12
                               Violet         11
                               Bronze          2
Name: count, dtype: int64

In [47]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'body_color', 'mode')
df['body_color'] = df_tmp['body_color']

#### Column: paint_type

In [48]:
df['paint_type'].value_counts(dropna=False)

paint_type
Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: count, dtype: int64

In [49]:
df.groupby(['make_model', 'body_type'])['paint_type'].value_counts(dropna=False)

make_model      body_type      paint_type
Audi A1         Compact        Metallic        723
                               NaN             311
                               Uni/basic         5
                Coupe          Metallic          2
                Other          Metallic         10
                               NaN               3
                Sedans         Metallic        990
                               NaN             490
                               Uni/basic        57
                               Perl effect       1
                Station wagon  Metallic         16
                               NaN               4
                               Uni/basic         1
                Van            Metallic          1
Audi A2         Off-Road       Metallic          1
Audi A3         Compact        Metallic        106
                               NaN              73
                               Uni/basic         3
                Convertible    Metallic          4
                               NaN               4
                Coupe          Metallic          4
                Other          Metallic         11
                               NaN               3
                               Uni/basic         2
                Sedans         Metallic       1498
                               NaN            1015
                               Uni/basic        92
                Station wagon  Metallic        169
                               NaN             113
Opel Astra      Compact        Metallic         98
                               NaN              87
                Coupe          Metallic          1
                               NaN               1
                Off-Road       Metallic          1
                Other          Metallic         43
                               NaN              24
                Sedans         Metallic        704
                               NaN             333
                               Uni/basic        15
                               Perl effect       1
                Station wagon  Metallic        866
                               NaN             340
                               Uni/basic        11
                               Perl effect       1
Opel Corsa      Compact        Metallic        744
                               NaN             486
                               Uni/basic         2
                Coupe          NaN               9
                               Metallic          3
                               Uni/basic         1
                Off-Road       NaN               3
                Other          Metallic         67
                               NaN              20
                Sedans         Metallic        466
                               NaN             358
                               Uni/basic        49
                               Perl effect       2
                Transporter    NaN               5
                               Metallic          1
                               Uni/basic         1
                Van            NaN               2
Opel Insignia   Compact        Metallic         21
                               NaN               6
                Coupe          NaN               1
                Off-Road       NaN               5
                               Metallic          2
                Other          Metallic         25
                               NaN              23
                Sedans         Metallic        579
                               NaN             310
                               Uni/basic        11
                Station wagon  Metallic       1152
                               NaN             450
                               Uni/basic        12
                Van            Metallic          1
Renault Clio    Compact        Metallic        281
                               NaN             201
                               Uni/basic         2
                Coupe          NaN               1
                Off-Road       Metallic          2
                Other          Metallic         31
                               NaN              20
                Sedans         NaN             511
                               Metallic        379
                               Uni/basic        43
                Station wagon  Metallic        167
                               NaN             164
                               Uni/basic         5
                               Perl effect       1
                Transporter    NaN              26
                               Uni/basic         2
                               Metallic          1
                Van            NaN               2
Renault Duster  Off-Road       NaN              17
                               Uni/basic        16
                               Metallic          1
Renault Espace  Compact        NaN               3
                               Metallic          2
                               Uni/basic         1
                Coupe          NaN               2
                Off-Road       Metallic          8
                Other          Metallic          5
                               Uni/basic         2
                               NaN               1
                Sedans         Metallic         11
                               NaN               7
                               Uni/basic         3
                Station wagon  Metallic         63
                               NaN              28
                Transporter    Metallic         34
                               NaN              18
                Van            Metallic        500
                               NaN             292
                               Uni/basic        11
Name: count, dtype: int64

In [50]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'paint_type', 'mode')
df['paint_type'] = df_tmp['paint_type']

#### Column: upholstery_texture

In [51]:
df['upholstery_texture'].value_counts(dropna=False)

upholstery_texture
Cloth           8423
NaN             4503
Part leather    1499
Full leather    1009
Other            368
Velour            60
Alcantara         57
Name: count, dtype: int64

In [52]:
df.groupby(['make_model', 'body_type'])['upholstery_texture'].value_counts(dropna=False)

make_model      body_type      upholstery_texture
Audi A1         Compact        Cloth                  807
                               NaN                    122
                               Part leather            48
                               Other                   34
                               Velour                  15
                               Alcantara                7
                               Full leather             6
                Coupe          Part leather             1
                               NaN                      1
                Other          Cloth                   12
                               NaN                      1
                Sedans         Cloth                  862
                               NaN                    518
                               Part leather            67
                               Other                   53
                               Full leather            18
                               Alcantara               10
                               Velour                  10
                Station wagon  Cloth                   15
                               NaN                      3
                               Part leather             2
                               Other                    1
                Van            NaN                      1
Audi A2         Off-Road       Cloth                    1
Audi A3         Compact        NaN                    104
                               Cloth                   44
                               Full leather            20
                               Part leather            14
                Convertible    Part leather             3
                               NaN                      3
                               Cloth                    2
                Coupe          Cloth                    3
                               NaN                      1
                Other          NaN                      6
                               Cloth                    5
                               Velour                   3
                               Part leather             2
                Sedans         Cloth                 1369
                               NaN                    864
                               Part leather           222
                               Full leather            67
                               Other                   60
                               Velour                  13
                               Alcantara               10
                Station wagon  Cloth                  187
                               NaN                     47
                               Part leather            37
                               Other                    5
                               Full leather             4
                               Alcantara                1
                               Velour                   1
Opel Astra      Compact        NaN                    118
                               Cloth                   57
                               Full leather             5
                               Part leather             3
                               Alcantara                2
                Coupe          Cloth                    1
                               Part leather             1
                Off-Road       Part leather             1
                Other          NaN                     61
                               Cloth                    5
                               Other                    1
                Sedans         Cloth                  737
                               NaN                    155
                               Part leather            77
                               Other                   44
                               Full leather            37
                               Velour                   2
                               Alcantara                1
                Station wagon  Cloth                  719
                               NaN                    221
                               Part leather           146
                               Other                   68
                               Full leather            54
                               Alcantara                8
                               Velour                   2
Opel Corsa      Compact        Cloth                 1066
                               NaN                    136
                               Part leather            15
                               Other                   10
                               Velour                   5
                Coupe          NaN                      7
                               Cloth                    5
                               Other                    1
                Off-Road       NaN                      3
                Other          NaN                     75
                               Cloth                   10
                               Full leather             1
                               Other                    1
                Sedans         Cloth                  590
                               NaN                    259
                               Other                    9
                               Part leather             9
                               Velour                   6
                               Alcantara                2
                Transporter    Cloth                    4
                               NaN                      3
                Van            NaN                      2
Opel Insignia   Compact        NaN                     10
                               Full leather             9
                               Part leather             6
                               Cloth                    2
                Coupe          NaN                      1
                Off-Road       NaN                      4
                               Cloth                    1
                               Full leather             1
                               Part leather             1
                Other          NaN                     43
                               Part leather             3
                               Cloth                    1
                               Other                    1
                Sedans         Cloth                  320
                               NaN                    293
                               Part leather           158
                               Full leather           119
                               Other                    6
                               Alcantara                4
                Station wagon  Cloth                  631
                               Part leather           369
                               Full leather           309
                               NaN                    283
                               Other                   19
                               Alcantara                2
                               Velour                   1
                Van            Cloth                    1
Renault Clio    Compact        Cloth                  221
                               NaN                    164
                               Part leather            81
                               Other                   10
                               Full leather             7
                               Alcantara                1
                Coupe          Full leather             1
                Off-Road       Cloth                    2
                Other          NaN                     36
                               Other                    6
                               Cloth                    4
                               Part leather             3
                               Alcantara                2
                Sedans         NaN                    430
                               Cloth                  404
                               Full leather            47
                               Part leather            40
                               Other                    9
                               Alcantara                2
                               Velour                   1
                Station wagon  Cloth                  197
                               NaN                    118
                               Part leather            12
                               Other                    6
                               Alcantara                2
                               Full leather             1
                               Velour                   1
                Transporter    NaN                     20
                               Cloth                    9
                Van            Cloth                    2
Renault Duster  Off-Road       Cloth                   18
                               NaN                     16
Renault Espace  Compact        NaN                      5
                               Cloth                    1
                Coupe          NaN                      2
                Off-Road       Full leather             3
                               Part leather             3
                               Alcantara                1
                               NaN                      1
                Other          Part leather             4
                               Full leather             3
                               NaN                      1
                Sedans         Part leather            10
                               Full leather             5
                               NaN                      5
                               Cloth                    1
                Station wagon  NaN                     39
                               Full leather            34
                               Cloth                   12
                               Part leather             5
                               Other                    1
                Transporter    NaN                     40
                               Full leather             6
                               Part leather             4
                               Cloth                    2
                Van            NaN                    281
                               Full leather           252
                               Part leather           152
                               Cloth                   93
                               Other                   23
                               Alcantara                2
Name: count, dtype: int64

In [53]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'upholstery_texture', 'mode')
df['upholstery_texture'] = df_tmp['upholstery_texture']

#### Column: upholstery_color

In [54]:
df['upholstery_color'].value_counts(dropna=False)

upholstery_color
Black     8201
NaN       5022
Grey      1376
Other     1016
Brown      207
Beige       54
Blue        16
White       13
Red          9
Yellow       4
Orange       1
Name: count, dtype: int64

In [55]:
df.groupby(['make_model', 'body_type'])['upholstery_color'].value_counts(dropna=False)

make_model      body_type      upholstery_color
Audi A1         Compact        Black                720
                               NaN                  137
                               Grey                 107
                               Other                 72
                               Blue                   3
                Coupe          Other                  1
                               NaN                    1
                Other          NaN                    7
                               Black                  6
                Sedans         Black                788
                               NaN                  534
                               Grey                 139
                               Other                 68
                               Blue                   4
                               Red                    3
                               Orange                 1
                               White                  1
                Station wagon  Black                 18
                               NaN                    2
                               Red                    1
                Van            Black                  1
Audi A2         Off-Road       Black                  1
Audi A3         Compact        Black                121
                               NaN                   48
                               Grey                   9
                               Other                  4
                Convertible    NaN                    4
                               Black                  2
                               Brown                  1
                               Other                  1
                Coupe          Black                  3
                               NaN                    1
                Other          Black                  6
                               NaN                    6
                               Grey                   4
                Sedans         Black               1171
                               NaN                  932
                               Grey                 292
                               Other                191
                               Brown                 13
                               Beige                  2
                               White                  2
                               Blue                   1
                               Yellow                 1
                Station wagon  Black                170
                               NaN                   72
                               Other                 32
                               Grey                   7
                               Blue                   1
Opel Astra      Compact        NaN                  103
                               Black                 75
                               Grey                   3
                               Other                  3
                               Beige                  1
                Coupe          Black                  1
                               Other                  1
                Off-Road       Grey                   1
                Other          NaN                   53
                               Black                 11
                               Grey                   2
                               Other                  1
                Sedans         Black                635
                               NaN                  260
                               Other                 94
                               Grey                  61
                               Beige                  3
                Station wagon  Black                698
                               NaN                  291
                               Other                126
                               Grey                  98
                               Beige                  2
                               Blue                   1
                               Brown                  1
                               White                  1
Opel Corsa      Compact        Black                886
                               NaN                  209
                               Grey                  90
                               Other                 47
                Coupe          NaN                    7
                               Black                  6
                Off-Road       NaN                    3
                Other          NaN                   74
                               Black                 11
                               Grey                   1
                               Other                  1
                Sedans         Black                386
                               NaN                  319
                               Grey                 120
                               Other                 45
                               Blue                   3
                               Brown                  1
                               White                  1
                Transporter    Black                  2
                               White                  2
                               NaN                    2
                               Grey                   1
                Van            NaN                    2
Opel Insignia   Compact        Black                 13
                               NaN                   12
                               Brown                  1
                               Other                  1
                Coupe          NaN                    1
                Off-Road       NaN                    5
                               Black                  1
                               Grey                   1
                Other          NaN                   41
                               Black                  4
                               Grey                   2
                               Other                  1
                Sedans         Black                508
                               NaN                  262
                               Other                 72
                               Grey                  44
                               Beige                 10
                               Brown                  2
                               Yellow                 2
                Station wagon  Black               1044
                               NaN                  338
                               Grey                 113
                               Other                 90
                               Beige                 21
                               Brown                  5
                               Blue                   1
                               White                  1
                               Yellow                 1
                Van            Grey                   1
Renault Clio    Compact        Black                224
                               NaN                  172
                               Grey                  50
                               Other                 38
                Coupe          Black                  1
                Off-Road       Black                  1
                               Grey                   1
                Other          Black                 25
                               NaN                   24
                               Grey                   1
                               Other                  1
                Sedans         NaN                  470
                               Black                320
                               Grey                  94
                               Other                 44
                               Red                    3
                               White                  2
                Station wagon  NaN                  142
                               Black                134
                               Grey                  48
                               Other                 11
                               Red                    2
                Transporter    NaN                   24
                               Grey                   3
                               Black                  2
                Van            Black                  1
                               NaN                    1
Renault Duster  Off-Road       Grey                  16
                               NaN                   16
                               Black                  2
Renault Espace  Compact        NaN                    6
                Coupe          NaN                    2
                Off-Road       Black                  3
                               NaN                    3
                               Brown                  1
                               Grey                   1
                Other          Beige                  2
                               Black                  2
                               Brown                  2
                               Grey                   1
                               NaN                    1
                Sedans         NaN                    8
                               Black                  7
                               Brown                  4
                               Grey                   2
                Station wagon  Grey                  26
                               NaN                   26
                               Black                 17
                               Brown                 13
                               Other                  9
                Transporter    NaN                   41
                               Brown                  5
                               White                  3
                               Grey                   2
                               Black                  1
                Van            NaN                  360
                               Black                173
                               Brown                158
                               Other                 62
                               Grey                  35
                               Beige                 13
                               Blue                   2
Name: count, dtype: int64

In [56]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'upholstery_color', 'mode')
df['upholstery_color'] = df_tmp['upholstery_color']

#### Column: country_version

In [57]:
df['country_version'].value_counts(dropna=False)

country_version
NaN               8333
Germany           4502
Italy             1038
European Union     507
Netherlands        464
Spain              325
Belgium            314
Austria            208
Czech Republic      52
Poland              49
France              38
Denmark             33
Hungary             28
Japan                8
Croatia              4
Slovakia             4
Sweden               3
Bulgaria             2
Romania              2
Switzerland          1
Luxembourg           1
Slovenia             1
Serbia               1
Egypt                1
Name: count, dtype: int64

In [58]:
df.groupby(['make_model', 'body_type'])['country_version'].value_counts(dropna=False)

make_model      body_type      country_version
Audi A1         Compact        Germany             448
                               NaN                 426
                               Netherlands          68
                               European Union       58
                               Denmark              15
                               Italy                 8
                               Austria               5
                               Belgium               5
                               France                2
                               Poland                2
                               Romania               1
                               Spain                 1
                Coupe          NaN                   2
                Other          NaN                   7
                               Italy                 5
                               Germany               1
                Sedans         NaN                 948
                               Germany             314
                               Italy               143
                               Spain                61
                               Belgium              43
                               Austria              14
                               European Union        9
                               France                3
                               Luxembourg            1
                               Slovakia              1
                               Switzerland           1
                Station wagon  NaN                  16
                               Germany               4
                               Spain                 1
                Van            NaN                   1
Audi A2         Off-Road       Germany               1
Audi A3         Compact        NaN                 131
                               Netherlands          33
                               Belgium              12
                               Germany               3
                               Austria               2
                               Italy                 1
                Convertible    NaN                   4
                               Italy                 2
                               Netherlands           2
                Coupe          NaN                   2
                               Belgium               1
                               Italy                 1
                Other          NaN                  14
                               Italy                 2
                Sedans         NaN                1624
                               Italy               334
                               Germany             306
                               European Union      173
                               Belgium              63
                               Spain                58
                               Poland               16
                               Austria              15
                               Czech Republic        6
                               France                3
                               Netherlands           3
                               Hungary               2
                               Slovenia              1
                               Sweden                1
                Station wagon  NaN                 105
                               Germany              70
                               European Union       46
                               Denmark              15
                               Italy                13
                               Czech Republic       12
                               Belgium              10
                               Hungary               4
                               France                3
                               Spain                 2
                               Austria               1
                               Sweden                1
Opel Astra      Compact        NaN                 130
                               Netherlands          35
                               Germany              20
                Coupe          Germany               2
                Off-Road       NaN                   1
                Other          NaN                  58
                               Italy                 3
                               Germany               2
                               Poland                2
                               Austria               1
                               European Union        1
                Sedans         NaN                 511
                               Germany             384
                               Spain                41
                               Italy                26
                               Belgium              22
                               European Union       20
                               Czech Republic       17
                               Netherlands          12
                               Austria               7
                               Poland                6
                               Croatia               2
                               Hungary               2
                               Egypt                 1
                               France                1
                               Romania               1
                Station wagon  NaN                 597
                               Germany             432
                               Italy                68
                               European Union       44
                               Netherlands          30
                               Czech Republic       14
                               Belgium              13
                               Austria               7
                               Spain                 6
                               Hungary               5
                               Poland                2
Opel Corsa      Compact        Germany             665
                               NaN                 436
                               European Union       54
                               Netherlands          40
                               Italy                14
                               Poland                9
                               Spain                 6
                               Austria               5
                               Croatia               2
                               Belgium               1
                Coupe          NaN                  10
                               Italy                 3
                Off-Road       NaN                   3
                Other          NaN                  78
                               Germany               7
                               Italy                 1
                               Netherlands           1
                Sedans         NaN                 488
                               Germany             168
                               Italy               156
                               Spain                28
                               Belgium              25
                               European Union        5
                               Austria               4
                               Netherlands           1
                Transporter    Italy                 2
                               Spain                 2
                               NaN                   2
                               Belgium               1
                Van            Austria               2
Opel Insignia   Compact        NaN                  16
                               Netherlands          10
                               Germany               1
                Coupe          NaN                   1
                Off-Road       NaN                   5
                               Belgium               1
                               Germany               1
                Other          NaN                  42
                               Germany               3
                               Spain                 2
                               Netherlands           1
                Sedans         NaN                 426
                               Germany             349
                               Netherlands          44
                               Spain                44
                               Belgium              10
                               Italy                 8
                               Austria               6
                               Poland                4
                               France                3
                               European Union        2
                               Hungary               2
                               Czech Republic        1
                               Slovakia              1
                Station wagon  NaN                 714
                               Germany             619
                               Netherlands          86
                               Italy                68
                               European Union       35
                               Belgium              30
                               Austria              23
                               Spain                15
                               Hungary              12
                               Poland                5
                               Denmark               2
                               Slovakia              2
                               Czech Republic        1
                               France                1
                               Sweden                1
                Van            Germany               1
Renault Clio    Compact        Germany             210
                               NaN                 169
                               European Union       39
                               Austria              28
                               Netherlands          22
                               Italy                 4
                               Spain                 4
                               Poland                3
                               France                2
                               Denmark               1
                               Hungary               1
                               Serbia                1
                Coupe          Germany               1
                Off-Road       Italy                 1
                               NaN                   1
                Other          NaN                  31
                               Austria              14
                               Italy                 5
                               Germany               1
                Sedans         NaN                 556
                               Germany             183
                               Italy                90
                               Spain                34
                               Belgium              32
                               France               15
                               European Union       11
                               Austria              10
                               Bulgaria              2
                Station wagon  NaN                 207
                               Germany              60
                               Italy                23
                               Netherlands          19
                               Austria               9
                               European Union        8
                               Belgium               7
                               France                3
                               Spain                 1
                Transporter    NaN                  24
                               Germany               2
                               Italy                 2
                               France                1
                Van            NaN                   2
Renault Duster  Off-Road       NaN                  25
                               Japan                 8
                               Belgium               1
Renault Espace  Compact        NaN                   6
                Coupe          NaN                   2
                Off-Road       NaN                   4
                               Italy                 3
                               Germany               1
                Other          NaN                   5
                               Germany               1
                               Italy                 1
                               Netherlands           1
                Sedans         NaN                  15
                               Germany               5
                               Belgium               1
                Station wagon  NaN                  65
                               Germany              25
                               Spain                 1
                Transporter    NaN                  44
                               Italy                 8
                Van            NaN                 379
                               Germany             212
                               Netherlands          56
                               Austria              55
                               Italy                43
                               Belgium              36
                               Spain                18
                               European Union        2
                               Czech Republic        1
                               France                1
Name: count, dtype: int64

In [59]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'country_version', 'mode')
df['country_version'] = df_tmp['country_version']

#### Column: entertainment_media

In [60]:
df['entertainment_media'].value_counts(dropna=False)

entertainment_media
NaN                                                                                                               1374
Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                                        1282
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                                                     982
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                                           783
On-board computer,Radio                                                                                            487
Radio                                                                                                              477
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,USB                                               465
On-board computer                                                                                                  461
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio                                               404
Bluetooth,On-board computer,Radio                                                                                  397
Bluetooth,Hands-free equipment,On-board computer,Radio                                                             378
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                              327
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio                                                         295
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio,USB                                           285
Bluetooth,Radio                                                                                                    271
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,USB                                       252
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio                                                   240
Bluetooth,On-board computer                                                                                        232
Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system,USB                                            188
Bluetooth,On-board computer,Radio,USB                                                                              180
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                175
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,USB                             157
Bluetooth,MP3,On-board computer,Radio,USB                                                                          154
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system,USB                              134
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                          130
Bluetooth,Hands-free equipment,On-board computer                                                                   130
Bluetooth                                                                                                          125
Bluetooth,Hands-free equipment,MP3,On-board computer,USB                                                           124
Bluetooth,Hands-free equipment                                                                                     121
Bluetooth,CD player,MP3,On-board computer,Radio                                                                    120
Bluetooth,Hands-free equipment,MP3,Radio,USB                                                                       115
Bluetooth,Hands-free equipment,On-board computer,USB                                                               115
CD player,On-board computer,Radio                                                                                  113
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                                        110
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system,USB                                  108
Bluetooth,CD player,On-board computer,Radio,USB                                                                    104
Bluetooth,CD player,MP3,On-board computer,Radio,USB                                                                102
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system                                   93
Bluetooth,Hands-free equipment,Radio,USB                                                                            93
Bluetooth,Digital radio,On-board computer,Radio,USB                                                                 87
Bluetooth,USB                                                                                                       83
Bluetooth,Hands-free equipment,Radio                                                                                83
Hands-free equipment,On-board computer,Radio,USB                                                                    81
Bluetooth,Hands-free equipment,MP3,On-board computer                                                                79
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio                                            78
Bluetooth,Radio,USB                                                                                                 74
CD player,MP3,On-board computer,Radio                                                                               73
Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system,USB                     70
Bluetooth,CD player,Radio,USB                                                                                       65
Bluetooth,CD player,On-board computer,Radio                                                                         63
On-board computer,Radio,USB                                                                                         59
CD player,MP3,Radio                                                                                                 57
Bluetooth,CD player,On-board computer                                                                               56
Bluetooth,MP3,On-board computer,Radio                                                                               56
Bluetooth,CD player,Hands-free equipment,MP3,Radio,USB                                                              56
Bluetooth,CD player,MP3,On-board computer                                                                           54
Bluetooth,MP3,On-board computer                                                                                     50
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system                                       50
USB                                                                                                                 46
Bluetooth,CD player,Hands-free equipment,MP3,Radio                                                                  43
Hands-free equipment,On-board computer,Radio                                                                        43
Bluetooth,On-board computer,Radio,Sound system                                                                      43
Hands-free equipment,On-board computer                                                                              42
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,Sound system                                             42
CD player,Radio                                                                                                     41
CD player,Hands-free equipment,Radio,Sound system                                                                   40
Bluetooth,Digital radio,MP3,On-board computer,Radio,USB                                                             39
MP3,On-board computer,Radio                                                                                         38
Digital radio,Hands-free equipment,On-board computer,Radio                                                          38
Bluetooth,Digital radio,Hands-free equipment,On-board computer,USB                                                  36
Digital radio,On-board computer,Radio                                                                               36
Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer,Radio,USB                                  36
MP3,Radio                                                                                                           36
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,USB                                              33
Bluetooth,CD player,Radio                                                                                           32
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio                                                32
Bluetooth,Hands-free equipment,MP3,Radio                                                                            30
Radio,USB                                                                                                           29
Bluetooth,On-board computer,USB                                                                                     28
CD player,On-board computer                                                                                         28
CD player                                                                                                           28
Bluetooth,CD player,MP3,On-board computer,Radio,Sound system,USB                                                    27
CD player,MP3,On-board computer,Radio,USB                                                                           27
Bluetooth,CD player,Digital radio,MP3,On-board computer,Radio,USB                                                   27
Bluetooth,CD player,Hands-free equipment,On-board computer,USB                                                      26
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio                                  25
Bluetooth,CD player,Hands-free equipment,Radio                                                                      25
On-board computer,Radio,Sound system                                                                                25
MP3,On-board computer,Radio,USB                                                                                     24
CD player,Hands-free equipment,On-board computer,Radio,USB                                                          24
CD player,Hands-free equipment,On-board computer                                                                    23
On-board computer,USB                                                                                               23
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Sound system,USB                                 23
Bluetooth,Hands-free equipment,MP3,On-board computer,Sound system,USB                                               23
Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system                                                 23
On-board computer,Sound system                                                                                      21
Radio,Sound system                                                                                                  21
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system                     20
Bluetooth,Digital radio,Hands-free equipment,Radio,USB                                                              20
Digital radio,Radio                                                                                                 20
CD player,Hands-free equipment,On-board computer,Radio                                                              19
Bluetooth,Hands-free equipment,MP3,USB                                                                              19
Bluetooth,Hands-free equipment,USB                                                                                  18
Bluetooth,CD player,MP3,Radio,USB                                                                                   18
Bluetooth,CD player,Hands-free equipment,On-board computer                                                          18
CD player,On-board computer,Radio,USB                                                                               17
Bluetooth,CD player,Hands-free equipment,Radio,USB                                                                  17
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,USB                                                  17
Bluetooth,CD player,MP3,On-board computer,Radio,Sound system                                                        16
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system                               16
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Sound system,USB                                     16
Bluetooth,Digital radio,Radio,USB                                                                                   16
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system                                   16
Bluetooth,Hands-free equipment,MP3,Radio,Sound system,USB                                                           16
Bluetooth,Digital radio,On-board computer                                                                           15
Bluetooth,MP3,On-board computer,USB                                                                                 15
Sound system                                                                                                        15
CD player,Hands-free equipment,Radio                                                                                15
Bluetooth,Hands-free equipment,On-board computer,Sound system,USB                                                   15
Bluetooth,Digital radio,Hands-free equipment,Radio,Sound system,USB                                                 14
MP3,On-board computer                                                                                               14
Bluetooth,CD player,On-board computer,USB                                                                           14
Hands-free equipment,Radio                                                                                          14
Bluetooth,CD player,Hands-free equipment,MP3,Radio,Sound system,USB                                                 14
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,USB                                    14
Bluetooth,CD player                                                                                                 14
Bluetooth,On-board computer,Radio,Sound system,USB                                                                  13
Bluetooth,Digital radio,On-board computer,Radio                                                                     13
Bluetooth,Digital radio,Hands-free equipment,MP3,Radio,Sound system,USB                                             13
Bluetooth,Digital radio,On-board computer,Radio,Sound system,USB                                                    13
Bluetooth,MP3,USB                                                                                                   13
Hands-free equipment                                                                                                13
Bluetooth,Hands-free equipment,Radio,Sound system,USB                                                               13
Bluetooth,CD player,MP3,Radio,Sound system,USB                                                                      13
CD player,Hands-free equipment                                                                                      13
Bluetooth,Digital radio,Hands-free equipment,MP3,Radio,USB                                                          13
Sound system,USB                                                                                                    12
CD player,MP3,On-board computer                                                                                     12
Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer,Radio                                      12
Hands-free equipment,On-board computer,USB                                                                          11
Bluetooth,CD player,Hands-free equipment                                                                            11
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,Television,USB      10
Bluetooth,CD player,MP3,Radio                                                                                       10
Bluetooth,Radio,Sound system,USB                                                                                    10
Bluetooth,Digital radio,On-board computer,USB                                                                       10
Digital radio,MP3,On-board computer,Radio                                                                           10
Bluetooth,CD player,Hands-free equipment,Radio,Sound system                                                         10
Bluetooth,CD player,Digital radio,MP3,On-board computer,Radio,Sound system,USB                                       9
MP3,On-board computer,USB                                                                                            9
Bluetooth,CD player,MP3,On-board computer,USB                                                                        8
Digital radio                                                                                                        8
CD player,Hands-free equipment,MP3,On-board computer,Radio                                                           8
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Sound system                                          8
Bluetooth,CD player,On-board computer,Radio,Sound system,USB                                                         8
Bluetooth,Hands-free equipment,MP3,On-board computer,Sound system                                                    8
Bluetooth,Digital radio,MP3,On-board computer,Radio,Sound system,USB                                                 8
Bluetooth,CD player,Digital radio,On-board computer,Radio,USB                                                        8
Bluetooth,MP3,On-board computer,Radio,Sound system,USB                                                               7
MP3,On-board computer,Radio,Sound system,USB                                                                         7
CD player,MP3,On-board computer,Radio,Sound system                                                                   7
Bluetooth,CD player,Digital radio,Hands-free equipment,Radio,USB                                                     7
Bluetooth,CD player,Hands-free equipment,On-board computer,Sound system,USB                                          7
Bluetooth,MP3,Radio,USB                                                                                              7
Bluetooth,Digital radio,Hands-free equipment,On-board computer                                                       7
CD player,Digital radio,MP3,On-board computer,Radio                                                                  7
Digital radio,Hands-free equipment,MP3,On-board computer,Radio                                                       7
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer                                                       7

In [61]:
df.groupby(['make_model', 'body_type'])['entertainment_media'].value_counts(dropna=False)

make_model      body_type      entertainment_media
Audi A1         Compact        Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                                          126
                               Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,USB                                               74
                               Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio                                               65
                               Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                              58
                               NaN                                                                                                                57
                               On-board computer,Radio                                                                                            41
                               Bluetooth,CD player,Hands-free equipment,On-board computer,Radio                                                   38
                               Radio                                                                                                              37
                               Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                                         35
                               Bluetooth,Hands-free equipment,MP3,Radio,USB                                                                       25
                               Bluetooth,CD player,MP3,On-board computer,Radio,USB                                                                24
                               Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system                                  22
                               Bluetooth,Radio                                                                                                    17
                               CD player,MP3,On-board computer,Radio                                                                              17
                               Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system                                      16
                               Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                15
                               Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,USB                             15
                               Bluetooth,CD player,MP3,On-board computer,Radio                                                                    13
                               CD player,MP3,Radio                                                                                                13
                               CD player,On-board computer,Radio                                                                                  13
                               Bluetooth,Hands-free equipment,MP3,On-board computer,Radio                                                         12
                               Bluetooth,Hands-free equipment,On-board computer,Radio                                                             11
                               Bluetooth,Hands-free equipment,Radio,USB                                                                           11
                               Bluetooth,CD player,On-board computer,Radio,USB                                                                    10
                               Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                                                     10
                               Bluetooth,Hands-free equipment,On-board computer                                                                   10
                               Bluetooth,Radio,USB                                                                                                10
                               CD player,Radio                                                                                                    10
                               Bluetooth,On-board computer,Radio                                                                                   9
                               On-board computer                                                                                                   9
                               Bluetooth,Hands-free equipment,MP3,On-board computer                                                                8
                               CD player,Hands-free equipment,On-board computer,Radio                                                              8
                               Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                                         7
                               Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system,USB                                             7
                               Bluetooth,MP3,On-board computer,Radio                                                                               7
                               Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system,USB                                   6
                               Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,Sound system                                             6
                               Bluetooth,Hands-free equipment,MP3,On-board computer,Sound system,USB                                               6
                               Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system                     5
                               Bluetooth,CD player,Hands-free equipment,MP3,Radio                                                                  5
                               Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system                                   5
                               Bluetooth,CD player,MP3,On-board computer,Radio,Sound system                                                        4
                               Bluetooth,Digital radio,Hands-free equipment,Sound system                                                           4
                               Bluetooth,Hands-free equipment                                                                                      4
                               Bluetooth,Hands-free equipment,MP3,On-board computer,USB                                                            4
                               Bluetooth,Hands-free equipment,Sound system,USB                                                                     4
                               MP3,On-board computer,Radio                                                                                         4
                               Bluetooth                                                                                                           3
                               Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system,USB                     3
                               Bluetooth,CD player,Hands-free equipment,On-board computer                                                          3
                               Bluetooth,CD player,MP3,Radio                                                                                       3
                               Bluetooth,CD player,On-board computer,Radio                                                                         3
                               Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Sound system,USB                                 3
                               Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio,USB                                            3
                               Bluetooth,Hands-free equipment,MP3                                                                                  3
                               Bluetooth,Hands-free equipment,MP3,Sound system,USB                                                                 3
                               Bluetooth,Hands-free equipment,On-board computer,Sound system                                                       3
                               CD player                                                                                                           3
                               CD player,MP3,On-board computer,Radio,Sound system                                                                  3
                               CD player,On-board computer,Radio,Sound system                                                                      3
                               Sound system                                                                                                        3
                               Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio                                  2
                               Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer                                            2
                               Bluetooth,CD player,Digital radio,MP3,On-board computer,Radio,USB                                                   2
                               Bluetooth,CD player,Hands-free equipment,On-board computer,Sound system                                             2
                               Bluetooth,CD player,Hands-free equipment,Radio                                                                      2
                               Bluetooth,CD player,Hands-free equipment,Radio,Sound system                                                         2
                               Bluetooth,CD player,On-board computer                                                                               2
                               Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                           2
                               Bluetooth,Digital radio,MP3,On-board computer,Radio,USB                                                             2
                               Bluetooth,Hands-free equipment,MP3,USB                                                                              2
                               Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system                                                 2
                               Bluetooth,Hands-free equipment,Radio                                                                                2
                               CD player,Digital radio,MP3,On-board computer,Radio                                                                 2
                               CD player,Hands-free equipment,MP3,On-board computer,Radio                                                          2
                               CD player,Hands-free equipment,On-board computer,Radio,Sound system                                                 2
                               CD player,MP3,On-board computer,Radio,USB                                                                           2
                               CD player,On-board computer                                                                                         2
                               MP3,On-board computer,USB                                                                                           2
                               On-board computer,Radio,USB                                                                                         2
                               Bluetooth,CD player                                                                                                 1
                               Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer,Radio,USB                                  1
                               Bluetooth,CD player,Digital radio,MP3,On-board computer,Radio,Sound system,USB                                      1
                               Bluetooth,CD player,Hands-free equipment                                                                            1
                               Bluetooth,CD player,Hands-free equipment,MP3,On-board computer                                                      1
                               Bluetooth,CD player,Hands-free equipment,MP3,Radio,Sound system,USB                                                 1
                               Bluetooth,CD player,Hands-free equipment,MP3,Radio,USB                                                              1
                               Bluetooth,CD player,Hands-free equipment,Sound system,USB                                                           1
                               Bluetooth,CD player,MP3,On-board computer,Radio,Sound system,USB                                                    1
                               Bluetooth,CD player,MP3,On-board computer,USB                                                                       1
                               Bluetooth,CD player,Radio                                                                                           1
                               Bluetooth,Digital radio,Hands-free equipment                                                                        1
                               Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio                                            1
                               Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system                               1
                               Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,USB                                        1
                               Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Sound system                                     1
                               Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,USB                                              1
                               Bluetooth,Digital radio,Hands-free equipment,On-board computer,USB                                                  1
                               Bluetooth,Digital radio,Hands-free equipment,Sound system,USB                                                       1
                               Bluetooth,Digital radio,On-board computer,USB                                                                       1
                               Bluetooth,Hands-free equipment,MP3,On-board computer,Sound system                                                   1
                               Bluetooth,Hands-free equipment,MP3,Radio                                                                            1
                               Bluetooth,Hands-free equipment,On-board computer,Sound system,USB                                                   1
                               Bluetooth,Hands-free equipment,On-board computer,USB                                                                1
                               Bluetooth,Hands-free equipment,Radio,Sound system,USB                                                               1
                               Bluetooth,Hands-free equipment,Sound system                                                                         1
                               Bluetooth,Hands-free equipment,USB                                                                                  1
                               Bluetooth,MP3,On-board computer                                                                                     1
                               Bluetooth,MP3,On-board computer,USB                                                                                 1
                               Bluetooth,MP3,Radio,USB                                                                                             1
                               Bluetooth,On-board computer                                                                                         1
                               Bluetooth,On-board computer,Radio,Sound system,USB                                                                  1
                               CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system                                             1
                               CD player,Hands-free equipment,On-board computer,Sound system,USB                                                   1
                               CD player,MP3,On-board computer,Radio,Sound system,USB                                                              1
                               CD player,MP3,Radio,Sound system,USB                                                                                1
                               CD player,On-board computer,Radio,USB                                                                               1
                               Hands-free equipment,MP3,On-board computer,USB                                                                      1
                               Hands-free equipment,On-board computer,Radio                                                                        1
                               MP3,Radio                                                                                                           1
                               MP3,USB                                                                                                             1
                               Radio,Sound system                                                                                                  1
                Coupe          Bluetooth,CD player,Hands-free equipment,On-board computer,Radio                                                    1
                               CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                                         1
                Other          CD player,Hands-free equipment,Radio                                                                                5
                               Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                                            2
                               Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,USB                                                2
                               Bluetooth,CD player,Hands-free equipment,On-board computer,Radio                                                    1
                               Bluetooth,Hands-free equipment,On-board computer,Radio                                                              1
                               Bluetooth,On-board computer,Radio                                                                                   1
                               CD player,On-board computer                                                                                         1
                Sedans         Radio                                                                                                             164
                               Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                                          116

In [62]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'entertainment_media', 'mode')
df['entertainment_media'] = df_tmp['entertainment_media']

#### Column: safety_security

In [63]:
df['safety_security'].value_counts(dropna=False)

Output hidden; open in https://colab.research.google.com to view.

In [64]:
df.groupby(['make_model', 'body_type'])['safety_security'].value_counts(dropna=False)

Output hidden; open in https://colab.research.google.com to view.

In [65]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'safety_security', 'mode')
df['safety_security'] = df_tmp['safety_security']

#### Column: comfort_convenience

In [66]:
df['comfort_convenience'].value_counts(dropna=False)

Output hidden; open in https://colab.research.google.com to view.

In [67]:
df.groupby(['make_model', 'body_type'])['comfort_convenience'].value_counts(dropna=False)

Output hidden; open in https://colab.research.google.com to view.

In [68]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'comfort_convenience', 'mode')
df['comfort_convenience'] = df_tmp['comfort_convenience']

#### Column: extras

In [69]:
df['extras'].value_counts(dropna=False)

extras
Alloy wheels                                                                                                                                   3245
NaN                                                                                                                                            2962
Alloy wheels,Touch screen                                                                                                                       697
Alloy wheels,Voice Control                                                                                                                      577
Alloy wheels,Touch screen,Voice Control                                                                                                         541
Alloy wheels,Roof rack                                                                                                                          385
Alloy wheels,Sport seats                                                                                                                        380
Roof rack                                                                                                                                       337
Alloy wheels,Catalytic Converter                                                                                                                271
Alloy wheels,Sport seats,Sport suspension                                                                                                       234
Alloy wheels,Catalytic Converter,Touch screen                                                                                                   228
Alloy wheels,Sport seats,Voice Control                                                                                                          226
Catalytic Converter                                                                                                                             224
Alloy wheels,Catalytic Converter,Voice Control                                                                                                  203
Alloy wheels,Roof rack,Touch screen,Voice Control                                                                                               192
Alloy wheels,Sport suspension                                                                                                                   177
Touch screen                                                                                                                                    169
Alloy wheels,Roof rack,Touch screen                                                                                                             164
Alloy wheels,Catalytic Converter,Touch screen,Voice Control                                                                                     132
Alloy wheels,Sport package                                                                                                                      113
Alloy wheels,Trailer hitch                                                                                                                      112
Alloy wheels,Sport suspension,Voice Control                                                                                                     110
Touch screen,Voice Control                                                                                                                      104
Alloy wheels,Sport seats,Touch screen                                                                                                            98
Alloy wheels,Sport package,Sport seats,Sport suspension                                                                                          94
Alloy wheels,Roof rack,Sport seats                                                                                                               93
Alloy wheels,Sport seats,Touch screen,Voice Control                                                                                              91
Alloy wheels,Roof rack,Sport seats,Touch screen,Voice Control                                                                                    87
Voice Control                                                                                                                                    85
Alloy wheels,Sport package,Sport seats                                                                                                           81
Alloy wheels,Sport package,Sport seats,Sport suspension,Voice Control                                                                            68
Alloy wheels,Catalytic Converter,Sport seats,Voice Control                                                                                       67
Alloy wheels,Cab or rented Car,Sport seats,Voice Control                                                                                         62
Alloy wheels,Roof rack,Voice Control                                                                                                             60
Alloy wheels,Catalytic Converter,Roof rack,Touch screen,Voice Control                                                                            57
Alloy wheels,Sport seats,Sport suspension,Voice Control                                                                                          57
Catalytic Converter,Touch screen                                                                                                                 55
Alloy wheels,Catalytic Converter,Roof rack,Touch screen                                                                                          53
Roof rack,Touch screen                                                                                                                           52
Alloy wheels,Roof rack,Ski bag,Sport seats,Touch screen,Voice Control                                                                            50
Roof rack,Touch screen,Voice Control                                                                                                             49
Alloy wheels,Roof rack,Trailer hitch                                                                                                             47
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                 46
Alloy wheels,Shift paddles                                                                                                                       45
Alloy wheels,Roof rack,Sport seats,Touch screen                                                                                                  38
Alloy wheels,Sport package,Sport seats,Voice Control                                                                                             38
Cab or rented Car                                                                                                                                37
Alloy wheels,Catalytic Converter,Sport seats,Sport suspension,Voice Control                                                                      34
Catalytic Converter,Touch screen,Voice Control                                                                                                   34
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension,Voice Control                                                        33
Roof rack,Voice Control                                                                                                                          33
Alloy wheels,Catalytic Converter,Roof rack,Sport seats,Touch screen,Voice Control                                                                32
Alloy wheels,Cab or rented Car                                                                                                                   32
Alloy wheels,Roof rack,Ski bag,Touch screen,Voice Control                                                                                        32
Alloy wheels,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                               31
Alloy wheels,Roof rack,Touch screen,Trailer hitch,Voice Control                                                                                  31
Alloy wheels,Roof rack,Sport suspension                                                                                                          31
Sport suspension                                                                                                                                 30
Trailer hitch                                                                                                                                    30
Alloy wheels,Catalytic Converter,Sport seats,Touch screen,Voice Control                                                                          30
Alloy wheels,Catalytic Converter,Roof rack,Voice Control                                                                                         29
Alloy wheels,Catalytic Converter,Roof rack                                                                                                       29
Sport seats                                                                                                                                      28
Alloy wheels,Catalytic Converter,Sport seats                                                                                                     26
Alloy wheels,Sport package,Voice Control                                                                                                         25
Roof rack,Sport seats                                                                                                                            25
Alloy wheels,Catalytic Converter,Shift paddles,Voice Control                                                                                     24
Alloy wheels,Catalytic Converter,Sport seats,Sport suspension                                                                                    24
Alloy wheels,Sport package,Sport seats,Touch screen,Voice Control                                                                                24
Roof rack,Trailer hitch                                                                                                                          23
Alloy wheels,Roof rack,Sport seats,Sport suspension,Trailer hitch,Voice Control                                                                  23
Alloy wheels,Roof rack,Sport seats,Sport suspension                                                                                              23
Catalytic Converter,Voice Control                                                                                                                22
Alloy wheels,Cab or rented Car,Sport seats                                                                                                       22
Alloy wheels,Winter tyres                                                                                                                        21
Alloy wheels,Shift paddles,Touch screen,Voice Control                                                                                            21
Roof rack,Sport seats,Touch screen,Voice Control                                                                                                 20
Sport seats,Sport suspension                                                                                                                     19
Alloy wheels,Roof rack,Sport package,Sport seats                                                                                                 19
Alloy wheels,Roof rack,Sport seats,Sport suspension,Touch screen,Voice Control                                                                   19
Catalytic Converter,Roof rack,Touch screen,Voice Control                                                                                         19
Catalytic Converter,Roof rack                                                                                                                    19
Alloy wheels,Sport package,Touch screen,Voice Control                                                                                            18
Alloy wheels,Shift paddles,Sport suspension                                                                                                      18
Alloy wheels,Touch screen,Trailer hitch,Voice Control                                                                                            18
Sport seats,Touch screen,Voice Control                                                                                                           18
Alloy wheels,Catalytic Converter,Sport package                                                                                                   17
Alloy wheels,Roof rack,Sport seats,Touch screen,Trailer hitch,Voice Control                                                                      17
Alloy wheels,Trailer hitch,Voice Control                                                                                                         17
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                     17
Alloy wheels,Shift paddles,Sport seats                                                                                                           16
Alloy wheels,Shift paddles,Voice Control                                                                                                         16
Alloy wheels,Catalytic Converter,Sport package,Sport seats                                                                                       16
Alloy wheels,Cab or rented Car,Catalytic Converter                                                                                               15
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension                                                                      14
Alloy wheels,Roof rack,Sport seats,Voice Control                                                                                                 14
Catalytic Converter,Roof rack,Touch screen                                                                                                       13
Alloy wheels,Sport package,Sport suspension,Voice Control                                                                                        13
Alloy wheels,Roof rack,Sport seats,Trailer hitch                                                                                                 13
Alloy wheels,Roof rack,Shift paddles                                                                                                             13
Alloy wheels,Ski bag,Sport seats,Touch screen,Voice Control                                                                                      13
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension,Touch screen,Trailer hitch,Voice Control                                       13
Alloy wheels,Touch screen,Trailer hitch                                                                                                          12
Winter tyres                                                                                                                                     12
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension,Voice Control                                                              12
Alloy wheels,Catalytic Converter,Roof rack,Touch screen,Trailer hitch,Voice Control                                                              12
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension                                                                                12
Catalytic Converter,Roof rack,Voice Control                                                                                                      12
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Touch screen,Voice Control                                                            12
Alloy wheels,Roof rack,Sport seats,Sport suspension,Touch screen,Trailer hitch,Voice Control                                                     11
Alloy wheels,Sport package,Sport seats,Sport suspension,Touch screen                                                                             11
Alloy wheels,Catalytic Converter,Shift paddles,Touch screen,Voice Control                                                                        11
Alloy wheels,Catalytic Converter,Sport package,Touch screen,Voice Control                                                                        11
Alloy wheels,Catalytic Converter,Sport seats,Touch screen                                                                                        11
Alloy wheels,Ski bag,Touch screen,Voice Control                                                                                                  11
Alloy wheels,Catalytic Converter,Sport suspension                                                                                                11
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension                                                                            11
Sport package                                                                                                                                    10
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Voice Control                                                                         10
Alloy wheels,Roof rack,Shift paddles,Touch screen,Voice Control                                                                                  10
Alloy wheels,Sport seats,Sport suspension,Trailer hitch                                                                                          10
Alloy wheels,Catalytic Converter,Winter tyres                                                                                                    10
Alloy wheels,Shift paddles,Sport seats,Sport suspension                                                                                          10
Alloy wheels,Sport suspension,Touch screen,Voice Control                                                                                         10
Alloy wheels,Sport package,Sport suspension                                                                                                      10
Alloy wheels,Sport seats,Trailer hitch                                                                                                           10
Alloy wheels,Catalytic Converter,Trailer hitch                                                                                                    9
Alloy wheels,Roof rack,Shift paddles,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                        9
Alloy wheels,Cab or rented Car,Roof rack                                                                                                          9
Alloy wheels,Cab or rented Car,Touch screen,Voice Control                                                                                         9
Alloy wheels,Cab or rented Car,Touch screen                                                                                                       9
Alloy wheels,Roof rack,Touch screen,Trailer hitch                                                                                                 9
Roof rack,Sport seats,Touch screen                                                                                                                8
Alloy wheels,Sport seats,Sport suspension,Touch screen,Voice Control                                                                              8
Alloy wheels,Catalytic Converter,Sport package,Voice Control                                                                                      8

In [70]:
df.groupby(['make_model', 'body_type'])['extras'].value_counts(dropna=False)

make_model      body_type      extras
Audi A1         Compact        Alloy wheels                                                                                                                                   185
                               NaN                                                                                                                                            110
                               Alloy wheels,Sport seats,Voice Control                                                                                                         109
                               Alloy wheels,Voice Control                                                                                                                      96
                               Alloy wheels,Catalytic Converter,Voice Control                                                                                                  68
                               Alloy wheels,Sport seats                                                                                                                        47
                               Alloy wheels,Catalytic Converter                                                                                                                31
                               Alloy wheels,Sport seats,Sport suspension                                                                                                       21
                               Alloy wheels,Cab or rented Car,Sport seats,Voice Control                                                                                        20
                               Alloy wheels,Catalytic Converter,Sport seats,Voice Control                                                                                      18
                               Alloy wheels,Sport package,Sport seats,Sport suspension,Voice Control                                                                           17
                               Alloy wheels,Catalytic Converter,Sport seats,Sport suspension                                                                                   16
                               Alloy wheels,Sport seats,Sport suspension,Voice Control                                                                                         15
                               Alloy wheels,Sport suspension                                                                                                                   12
                               Voice Control                                                                                                                                   12
                               Alloy wheels,Catalytic Converter,Sport seats,Sport suspension,Voice Control                                                                     11
                               Alloy wheels,Sport package,Sport seats,Sport suspension                                                                                         11
                               Alloy wheels,Touch screen,Voice Control                                                                                                         11
                               Catalytic Converter                                                                                                                             11
                               Alloy wheels,Cab or rented Car,Sport seats                                                                                                       9
                               Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension,Voice Control                                                        9
                               Alloy wheels,Catalytic Converter,Sport package,Touch screen,Voice Control                                                                        9
                               Alloy wheels,Catalytic Converter,Touch screen,Voice Control                                                                                      9
                               Alloy wheels,Cab or rented Car                                                                                                                   8
                               Alloy wheels,Catalytic Converter,Sport seats                                                                                                     8
                               Alloy wheels,Catalytic Converter,Sport package                                                                                                   7
                               Alloy wheels,Catalytic Converter,Winter tyres                                                                                                    7
                               Alloy wheels,Sport package,Sport seats                                                                                                           7
                               Alloy wheels,Sport package,Sport suspension                                                                                                      7
                               Alloy wheels,Sport package,Voice Control                                                                                                         7
                               Catalytic Converter,Voice Control                                                                                                                7
                               Alloy wheels,Catalytic Converter,Sport suspension                                                                                                6
                               Alloy wheels,Sport package                                                                                                                       6
                               Alloy wheels,Sport seats,Touch screen                                                                                                            6
                               Alloy wheels,Cab or rented Car,Sport seats,Sport suspension,Voice Control                                                                        5
                               Alloy wheels,Catalytic Converter,Sport package,Sport seats,Touch screen                                                                          5
                               Alloy wheels,Touch screen                                                                                                                        5
                               Sport suspension                                                                                                                                 5
                               Alloy wheels,Catalytic Converter,Sport package,Sport seats                                                                                       4
                               Alloy wheels,Sport package,Sport seats,Touch screen,Voice Control                                                                                4
                               Alloy wheels,Sport suspension,Voice Control                                                                                                      4
                               Alloy wheels,Cab or rented Car,Voice Control                                                                                                     3
                               Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension                                                                      3
                               Alloy wheels,Catalytic Converter,Sport package,Voice Control                                                                                     3
                               Alloy wheels,Sport package,Sport seats,Voice Control                                                                                             3
                               Alloy wheels,Catalytic Converter,Sport package,Sport seats,Voice Control                                                                         2
                               Alloy wheels,Catalytic Converter,Sport package,Sport suspension,Voice Control                                                                    2
                               Alloy wheels,Shift paddles,Sport seats                                                                                                           2
                               Alloy wheels,Shift paddles,Sport seats,Sport suspension                                                                                          2
                               Alloy wheels,Shift paddles,Voice Control                                                                                                         2
                               Alloy wheels,Sport package,Sport suspension,Voice Control                                                                                        2
                               Catalytic Converter,Sport package                                                                                                                2
                               Catalytic Converter,Touch screen,Voice Control                                                                                                   2
                               Catalytic Converter,Winter tyres                                                                                                                 2
                               Touch screen                                                                                                                                     2
                               Alloy wheels,Cab or rented Car,Catalytic Converter                                                                                               1
                               Alloy wheels,Cab or rented Car,Catalytic Converter,Sport package,Sport seats,Sport suspension,Voice Control                                      1
                               Alloy wheels,Cab or rented Car,Catalytic Converter,Sport package,Sport suspension                                                                1
                               Alloy wheels,Cab or rented Car,Catalytic Converter,Sport suspension                                                                              1
                               Alloy wheels,Cab or rented Car,Catalytic Converter,Voice Control                                                                                 1
                               Alloy wheels,Cab or rented Car,Sport suspension,Voice Control                                                                                    1
                               Alloy wheels,Catalytic Converter,Shift paddles                                                                                                   1
                               Alloy wheels,Catalytic Converter,Shift paddles,Sport package,Sport suspension,Voice Control                                                      1
                               Alloy wheels,Catalytic Converter,Shift paddles,Sport seats,Voice Control                                                                         1
                               Alloy wheels,Catalytic Converter,Sport package,Sport seats,Touch screen,Voice Control                                                            1
                               Alloy wheels,Catalytic Converter,Sport seats,Sport suspension,Touch screen,Voice Control                                                         1
                               Alloy wheels,Catalytic Converter,Sport seats,Touch screen,Voice Control                                                                          1
                               Alloy wheels,Catalytic Converter,Sport suspension,Voice Control                                                                                  1
                               Alloy wheels,Shift paddles                                                                                                                       1
                               Alloy wheels,Shift paddles,Sport seats,Sport suspension,Voice Control                                                                            1
                               Alloy wheels,Shift paddles,Sport seats,Touch screen                                                                                              1
                               Alloy wheels,Shift paddles,Sport suspension,Voice Control                                                                                        1
                               Alloy wheels,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                               1
                               Alloy wheels,Sport package,Sport seats,Sport suspension,Tuned car,Winter tyres                                                                   1
                               Alloy wheels,Sport package,Touch screen,Voice Control                                                                                            1
                               Alloy wheels,Sport seats,Sport suspension,Trailer hitch,Voice Control                                                                            1
                               Alloy wheels,Sport seats,Sport suspension,Voice Control,Winter tyres                                                                             1
                               Alloy wheels,Sport seats,Touch screen,Voice Control                                                                                              1
                               Alloy wheels,Sport seats,Voice Control,Winter tyres                                                                                              1
                               Alloy wheels,Sport suspension,Touch screen                                                                                                       1
                               Alloy wheels,Winter tyres                                                                                                                        1
                               Cab or rented Car,Catalytic Converter,Voice Control                                                                                              1
                               Cab or rented Car,Sport suspension                                                                                                               1
                               Catalytic Converter,Shift paddles,Sport package,Sport seats,Sport suspension                                                                     1
                               Catalytic Converter,Sport package,Sport suspension                                                                                               1
                               Catalytic Converter,Sport seats                                                                                                                  1
                               Catalytic Converter,Sport seats,Sport suspension                                                                                                 1
                               Catalytic Converter,Sport suspension,Voice Control                                                                                               1
                               Catalytic Converter,Touch screen                                                                                                                 1
                               Ski bag                                                                                                                                          1
                               Ski bag,Sport suspension                                                                                                                         1
                               Sport package,Sport seats,Sport suspension,Voice Control                                                                                         1
                               Sport package,Sport suspension                                                                                                                   1
                               Sport seats                                                                                                                                      1
                               Sport seats,Sport suspension                                                                                                                     1
                               Sport seats,Sport suspension,Voice Control                                                                                                       1
                               Touch screen,Voice Control                                                                                                                       1
                Coupe          Alloy wheels,Catalytic Converter                                                                                                                 1
                               Alloy wheels,Catalytic Converter,Sport seats,Sport suspension,Voice Control                                                                      1
                Other          Alloy wheels                                                                                                                                     7
                               Alloy wheels,Cab or rented Car,Sport seats                                                                                                       1
                               Alloy wheels,Catalytic Converter,Shift paddles,Sport package,Sport seats,Touch screen                                                            1
                               Alloy wheels,Catalytic Converter,Shift paddles,Touch screen                                                                                      1
                               Alloy wheels,Shift paddles,Touch screen                                                                                                          1
                               Alloy wheels,Voice Control                                                                                                                       1
                               Roof rack,Sport seats                                                                                                                            1
                Sedans         Alloy wheels                                                                                                                                   422
                               NaN                                                                                                                                            173
                               Alloy wheels,Sport seats                                                                                                                       114
                               Alloy wheels,Voice Control                                                                                                                      87
                               Alloy wheels,Sport seats,Voice Control                                                                                                          79
                               Alloy wheels,Sport seats,Sport suspension                                                                                                       57

In [71]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'extras', 'mode')
#df_tmp['extras'].isnull().sum()
#df_tmp['extras'].value_counts(dropna=False)
df['extras'] = df_tmp['extras']

#### Column: nr_of_doors

In [72]:
df['nr_of_doors'].value_counts(dropna=False)

nr_of_doors
5.0    11575
4.0     3079
3.0      832
2.0      219
NaN      212
1.0        1
7.0        1
Name: count, dtype: int64

In [73]:
df.groupby(['make_model', 'body_type'])['nr_of_doors'].value_counts(dropna=False)

make_model      body_type      nr_of_doors
Audi A1         Compact        5.0             666
                               4.0             207
                               3.0              80
                               2.0              69
                               NaN              17
                Coupe          2.0               1
                               5.0               1
                Other          5.0               8
                               4.0               5
                Sedans         5.0            1048
                               4.0             321
                               3.0             130
                               2.0              29
                               NaN              10
                Station wagon  5.0              17
                               4.0               3
                               3.0               1
                Van            5.0               1
Audi A2         Off-Road       5.0               1
Audi A3         Compact        5.0             164
                               3.0              11
                               4.0               6
                               NaN               1
                Convertible    2.0               7
                               5.0               1
                Coupe          3.0               4
                Other          5.0              10
                               3.0               3
                               2.0               2
                               4.0               1
                Sedans         5.0            1953
                               4.0             517
                               3.0              94
                               NaN              24
                               2.0              17
                Station wagon  5.0             169
                               4.0             110
                               2.0               1
                               3.0               1
                               NaN               1
Opel Astra      Compact        5.0             180
                               4.0               5
                Coupe          3.0               1
                               5.0               1
                Off-Road       5.0               1
                Other          5.0              59
                               4.0               7
                               NaN               1
                Sedans         5.0             797
                               4.0             241
                               NaN              12
                               3.0               3
                Station wagon  5.0             927
                               4.0             280
                               NaN              11
Opel Corsa      Compact        5.0             528
                               3.0             338
                               4.0             268
                               2.0              88
                               NaN              10
                Coupe          3.0              12
                               5.0               1
                Off-Road       5.0               3
                Other          5.0              80
                               3.0               4
                               4.0               2
                               2.0               1
                Sedans         5.0             662
                               3.0             146
                               NaN              42
                               4.0              21
                               2.0               4
                Transporter    3.0               4
                               5.0               3
                Van            NaN               2
Opel Insignia   Compact        5.0              26
                               4.0               1
                Coupe          4.0               1
                Off-Road       5.0               7
                Other          5.0              44
                               4.0               3
                               NaN               1
                Sedans         5.0             638
                               4.0             250
                               NaN              12
                Station wagon  5.0            1149
                               4.0             453
                               NaN              12
                Van            5.0               1
Renault Clio    Compact        5.0             302
                               4.0             170
                               NaN              11
                               1.0               1
                Coupe          4.0               1
                Off-Road       5.0               2
                Other          5.0              46
                               4.0               4
                               NaN               1
                Sedans         5.0             868
                               4.0              44
                               NaN              21
                Station wagon  5.0             276
                               4.0              52
                               NaN               9
                Transporter    5.0              27
                               4.0               1
                               NaN               1
                Van            5.0               1
                               NaN               1
Renault Duster  Off-Road       5.0              34
Renault Espace  Compact        5.0               5
                               4.0               1
                Coupe          5.0               1
                               NaN               1
                Off-Road       5.0               6
                               4.0               1
                               NaN               1
                Other          5.0               7
                               NaN               1
                Sedans         5.0              12
                               4.0               9
                Station wagon  5.0              86
                               4.0               4
                               NaN               1
                Transporter    5.0              52
                Van            5.0             704
                               4.0              90
                               NaN               8
                               7.0               1
Name: count, dtype: int64

In [74]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'nr_of_doors', 'mode')
df['nr_of_doors'] = df_tmp['nr_of_doors']

#### Column: nr_of_seats

In [75]:
df['nr_of_seats'].value_counts(dropna=False)

nr_of_seats
5.0    13336
4.0     1125
NaN      977
7.0      362
2.0      116
6.0        2
3.0        1
Name: count, dtype: int64

In [76]:
df.groupby(['make_model', 'body_type'])['nr_of_seats'].value_counts(dropna=False)

make_model      body_type      nr_of_seats
Audi A1         Compact        5.0             538
                               4.0             431
                               NaN              68
                               3.0               1
                               6.0               1
                Coupe          4.0               1
                               5.0               1
                Other          5.0              12
                               4.0               1
                Sedans         5.0             827
                               4.0             641
                               NaN              70
                Station wagon  5.0              14
                               4.0               6
                               NaN               1
                Van            NaN               1
Audi A2         Off-Road       5.0               1
Audi A3         Compact        5.0             175
                               NaN               7
                Convertible    4.0               5
                               5.0               2
                               NaN               1
                Coupe          5.0               4
                Other          5.0               9
                               NaN               6
                               4.0               1
                Sedans         5.0            2484
                               NaN             102
                               4.0              19
                Station wagon  5.0             277
                               NaN               5
Opel Astra      Compact        5.0             174
                               NaN              11
                Coupe          4.0               1
                               NaN               1
                Off-Road       5.0               1
                Other          5.0              61
                               NaN               6
                Sedans         5.0             985
                               NaN              68
                Station wagon  5.0            1136
                               NaN              78
                               4.0               4
Opel Corsa      Compact        5.0            1200
                               NaN              27
                               4.0               5
                Coupe          5.0              11
                               2.0               1
                               NaN               1
                Off-Road       NaN               2
                               5.0               1
                Other          5.0              86
                               NaN               1
                Sedans         5.0             787
                               NaN              87
                               4.0               1
                Transporter    2.0               4
                               5.0               2
                               4.0               1
                Van            NaN               2
Opel Insignia   Compact        5.0              26
                               NaN               1
                Coupe          NaN               1
                Off-Road       5.0               7
                Other          5.0              44
                               NaN               4
                Sedans         5.0             857
                               NaN              43
                Station wagon  5.0            1552
                               NaN              59
                               4.0               2
                               2.0               1
                Van            5.0               1
Renault Clio    Compact        5.0             406
                               NaN              70
                               2.0               8
                Coupe          5.0               1
                Off-Road       5.0               2
                Other          5.0              43
                               2.0               4
                               NaN               4
                Sedans         5.0             760
                               NaN              99
                               2.0              71
                               4.0               3
                Station wagon  5.0             307
                               NaN              28
                               4.0               2
                Transporter    2.0              26
                               NaN               3
                Van            2.0               1
                               5.0               1
Renault Duster  Off-Road       5.0              34
Renault Espace  Compact        5.0               3
                               7.0               2
                               NaN               1
                Coupe          NaN               2
                Off-Road       5.0               5
                               7.0               3
                Other          5.0               4
                               7.0               3
                               NaN               1
                Sedans         5.0              11
                               NaN               6
                               7.0               4
                Station wagon  5.0              66
                               7.0              19
                               NaN               5
                               6.0               1
                Transporter    5.0              35
                               7.0              16
                               NaN               1
                Van            5.0             383
                               7.0             315
                               NaN             104
                               4.0               1
Name: count, dtype: int64

In [77]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'nr_of_seats', 'mode')
df['nr_of_seats'] = df_tmp['nr_of_seats']

#### Column: weight

In [78]:
df['weight'].isnull().groupby([df['make_model'], df['body_type']]).sum()

make_model      body_type
Audi A1         Compact          526
                Coupe              1
                Other              9
                Sedans           613
                Station wagon      7
                Van                1
Audi A2         Off-Road           1
Audi A3         Compact           25
                Convertible        1
                Coupe              1
                Other             13
                Sedans           978
                Station wagon    169
Opel Astra      Compact           72
                Coupe              1
                Off-Road           0
                Other             13
                Sedans           553
                Station wagon    622
Opel Corsa      Compact          724
                Coupe              3
                Off-Road           0
                Other              8
                Sedans           241
                Transporter        1
                Van                0
Opel Insignia   Compact            7
                Coupe              1
                Off-Road           1
                Other              9
                Sedans           389
                Station wagon    845
                Van                1
Renault Clio    Compact          252
                Coupe              1
                Off-Road           0
                Other             23
                Sedans           276
                Station wagon    107
                Transporter       21
                Van                2
Renault Duster  Off-Road          34
Renault Espace  Compact            4
                Coupe              2
                Off-Road           4
                Other              3
                Sedans            19
                Station wagon     13
                Transporter        3
                Van              374
Name: weight, dtype: int64

In [79]:
df['weight'].describe()

count    8945.000000
mean     1351.106540
std       220.661532
min         1.000000
25%      1165.000000
50%      1288.000000
75%      1487.000000
max      2471.000000
Name: weight, dtype: float64

In [80]:
df.groupby(['make_model', 'body_type'])['weight'].median()

make_model      body_type
Audi A1         Compact          1180.0
                Coupe            1010.0
                Other            1217.5
                Sedans           1195.0
                Station wagon    1205.0
                Van                 NaN
Audi A2         Off-Road            NaN
Audi A3         Compact          1280.0
                Convertible      1555.0
                Coupe            1250.0
                Other            1355.0
                Sedans           1350.0
                Station wagon    1335.0
Opel Astra      Compact          1325.0
                Coupe            1350.0
                Off-Road         1340.0
                Other            1350.0
                Sedans           1308.0
                Station wagon    1393.0
Opel Corsa      Compact          1163.0
                Coupe            1159.5
                Off-Road         1163.0
                Other            1163.0
                Sedans           1163.0
                Transporter      1181.0
                Van              1124.0
Opel Insignia   Compact          1487.5
                Coupe               NaN
                Off-Road         1487.0
                Other            1503.0
                Sedans           1503.0
                Station wagon    1623.0
                Van                 NaN
Renault Clio    Compact          1090.0
                Coupe               NaN
                Off-Road         1163.5
                Other            1091.0
                Sedans           1162.0
                Station wagon    1175.0
                Transporter      1181.5
                Van                 NaN
Renault Duster  Off-Road            NaN
Renault Espace  Compact          1690.5
                Coupe               NaN
                Off-Road         1734.0
                Other            1734.0
                Sedans           1864.5
                Station wagon    1684.0
                Transporter      1734.0
                Van              1685.0
Name: weight, dtype: float64

In [81]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'weight', 'median')
df['weight'] = df_tmp['weight']

#### Column: drive_chain

In [82]:
df['drive_chain'].value_counts(dropna=False)

drive_chain
Front    8886
NaN      6858
4wd       171
Rear        4
Name: count, dtype: int64

In [83]:
df.groupby(['make_model', 'body_type'])['drive_chain'].value_counts(dropna=False)

make_model      body_type      drive_chain
Audi A1         Compact        Front           685
                               NaN             352
                               4wd               2
                Coupe          NaN               2
                Other          Front            12
                               NaN               1
                Sedans         Front           977
                               NaN             560
                               4wd               1
                Station wagon  Front            18
                               NaN               3
                Van            Front             1
Audi A2         Off-Road       Front             1
Audi A3         Compact        Front           156
                               NaN              25
                               4wd               1
                Convertible    NaN               4
                               Front             3
                               4wd               1
                Coupe          Front             3
                               NaN               1
                Other          Front            10
                               NaN               6
                Sedans         Front          1703
                               NaN             885
                               4wd              17
                Station wagon  NaN             149
                               Front           133
Opel Astra      Compact        Front           104
                               NaN              81
                Coupe          NaN               2
                Off-Road       Front             1
                Other          NaN              62
                               Front             5
                Sedans         Front           544
                               NaN             507
                               4wd               2
                Station wagon  Front           692
                               NaN             526
Opel Corsa      Compact        Front           631
                               NaN             601
                Coupe          Front             7
                               NaN               6
                Off-Road       NaN               3
                Other          NaN              77
                               Front            10
                Sedans         Front           516
                               NaN             359
                Transporter    Front             6
                               NaN               1
                Van            NaN               2
Opel Insignia   Compact        NaN              17
                               Front            10
                Coupe          NaN               1
                Off-Road       4wd               5
                               Front             1
                               NaN               1
                Other          NaN              47
                               Front             1
                Sedans         Front           505
                               NaN             368
                               4wd              26
                               Rear              1
                Station wagon  Front           891
                               NaN             658
                               4wd              63
                               Rear              2
                Van            Front             1
Renault Clio    Compact        NaN             270
                               Front           213
                               4wd               1
                Coupe          Front             1
                Off-Road       Front             1
                               NaN               1
                Other          Front            26
                               NaN              25
                Sedans         NaN             533
                               Front           390
                               4wd               9
                               Rear              1
                Station wagon  NaN             181
                               Front           155
                               4wd               1
                Transporter    NaN              21
                               Front             8
                Van            Front             1
                               NaN               1
Renault Duster  Off-Road       NaN              32
                               4wd               2
Renault Espace  Compact        NaN               5
                               Front             1
                Coupe          NaN               2
                Off-Road       NaN               5
                               Front             3
                Other          Front             5
                               NaN               3
                Sedans         NaN              16
                               Front             5
                Station wagon  Front            70
                               NaN              20
                               4wd               1
                Transporter    NaN              45
                               Front             6
                               4wd               1
                Van            NaN             391
                               Front           374
                               4wd              38
Name: count, dtype: int64

In [84]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'drive_chain', 'mode')
df['drive_chain'] = df_tmp['drive_chain']

#### Column: gearing_type

In [85]:
df['gearing_type'].value_counts(dropna=False)

gearing_type
Manual            8153
Automatic         7297
Semi-automatic     469
Name: count, dtype: int64

In [86]:
df.groupby(['make_model', 'body_type'])['gearing_type'].value_counts(dropna=False)

make_model      body_type      gearing_type
Audi A1         Compact        Manual             574
                               Automatic          462
                               Semi-automatic       3
                Coupe          Manual               2
                Other          Manual               9
                               Automatic            3
                               Semi-automatic       1
                Sedans         Manual             807
                               Automatic          678
                               Semi-automatic      53
                Station wagon  Manual              13
                               Automatic            8
                Van            Automatic            1
Audi A2         Off-Road       Manual               1
Audi A3         Compact        Manual              98
                               Automatic           70
                               Semi-automatic      14
                Convertible    Semi-automatic       5
                               Automatic            3
                Coupe          Automatic            4
                Other          Manual               8
                               Automatic            5
                               Semi-automatic       3
                Sedans         Manual            1199
                               Automatic         1169
                               Semi-automatic     237
                Station wagon  Manual             172
                               Automatic          109
                               Semi-automatic       1
Opel Astra      Compact        Manual             137
                               Automatic           43
                               Semi-automatic       5
                Coupe          Automatic            2
                Off-Road       Automatic            1
                Other          Manual              62
                               Automatic            5
                Sedans         Manual             643
                               Automatic          402
                               Semi-automatic       8
                Station wagon  Automatic          640
                               Manual             573
                               Semi-automatic       5
Opel Corsa      Compact        Automatic          616
                               Manual             596
                               Semi-automatic      20
                Coupe          Manual              10
                               Automatic            2
                               Semi-automatic       1
                Off-Road       Manual               3
                Other          Manual              74
                               Automatic           13
                Sedans         Manual             607
                               Automatic          239
                               Semi-automatic      29
                Transporter    Manual               7
                Van            Manual               2
Opel Insignia   Compact        Manual              17
                               Automatic           10
                Coupe          Manual               1
                Off-Road       Automatic            4
                               Manual               3
                Other          Manual              40
                               Automatic            8
                Sedans         Manual             535
                               Automatic          365
                Station wagon  Automatic          937
                               Manual             677
                Van            Manual               1
Renault Clio    Compact        Manual             280
                               Automatic          203
                               Semi-automatic       1
                Coupe          Automatic            1
                Off-Road       Automatic            1
                               Manual               1
                Other          Manual              30
                               Automatic           21
                Sedans         Manual             611
                               Automatic          284
                               Semi-automatic      38
                Station wagon  Manual             221
                               Automatic          110
                               Semi-automatic       6
                Transporter    Manual              29
                Van            Manual               2
Renault Duster  Off-Road       Manual              26
                               Automatic            8
Renault Espace  Compact        Automatic            6
                Coupe          Automatic            2
                Off-Road       Automatic            7
                               Manual               1
                Other          Automatic            6
                               Manual               2
                Sedans         Automatic           18
                               Manual               3
                Station wagon  Automatic           84
                               Manual               6
                               Semi-automatic       1
                Transporter    Automatic           23
                               Semi-automatic      22
                               Manual               7
                Van            Automatic          724
                               Manual              63
                               Semi-automatic      16
Name: count, dtype: int64

In [87]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'gearing_type', 'mode')
df['gearing_type'] = df_tmp['gearing_type']

#### Column: gears

In [88]:
df['gears'].value_counts(dropna=False)

gears
6.0     5822
NaN     4712
5.0     3239
7.0     1908
8.0      224
9.0        6
1.0        2
4.0        2
3.0        2
2.0        1
50.0       1
Name: count, dtype: int64

In [89]:
df.groupby(['make_model', 'body_type'])['gears'].value_counts(dropna=False)

make_model      body_type      gears
Audi A1         Compact        NaN       473
                               5.0       280
                               7.0       202
                               6.0        83
                               8.0         1
                Coupe          5.0         1
                               NaN         1
                Other          NaN         5
                               5.0         4
                               7.0         4
                Sedans         5.0       523
                               NaN       466
                               7.0       447
                               6.0       101
                               8.0         1
                Station wagon  5.0        10
                               NaN         7
                               7.0         3
                               6.0         1
                Van            6.0         1
Audi A2         Off-Road       NaN         1
Audi A3         Compact        6.0        92
                               7.0        70
                               NaN        19
                               5.0         1
                Convertible    7.0         6
                               6.0         2
                Coupe          7.0         4
                Other          7.0         8
                               6.0         5
                               NaN         3
                Sedans         6.0      1048
                               7.0       982
                               NaN       574
                               5.0         1
                Station wagon  NaN       130
                               6.0       111
                               7.0        41
Opel Astra      Compact        6.0       135
                               5.0        33
                               NaN        17
                Coupe          6.0         1
                               NaN         1
                Off-Road       6.0         1
                Other          6.0        54
                               NaN         9
                               5.0         4
                Sedans         6.0       456
                               NaN       337
                               5.0       260
                Station wagon  6.0       701
                               NaN       428
                               5.0        88
                               7.0         1
Opel Corsa      Compact        NaN       482
                               5.0       466
                               6.0       282
                               1.0         1
                               8.0         1
                Coupe          5.0        10
                               NaN         2
                               6.0         1
                Off-Road       5.0         2
                               6.0         1
                Other          5.0        70
                               6.0        11
                               NaN         6
                Sedans         5.0       588
                               6.0       167
                               NaN       119
                               2.0         1
                Transporter    5.0         7
                Van            NaN         2
Opel Insignia   Compact        6.0        25
                               8.0         1
                               NaN         1
                Coupe          NaN         1
                Off-Road       6.0         4
                               8.0         2
                               NaN         1
                Other          6.0        39
                               NaN         8
                               8.0         1
                Sedans         6.0       657
                               NaN       187
                               8.0        51
                               5.0         4
                               7.0         1
                Station wagon  6.0       947
                               NaN       497
                               8.0       166
                               5.0         3
                               7.0         1
                Van            6.0         1
Renault Clio    Compact        NaN       250
                               5.0       162
                               6.0        69
                               7.0         2
                               1.0         1
                Coupe          6.0         1
                Off-Road       5.0         1
                               6.0         1
                Other          NaN        26
                               5.0        19
                               6.0         6
                Sedans         5.0       529
                               6.0       233
                               NaN       170
                               50.0        1
                Station wagon  5.0       160
                               NaN        95
                               6.0        81
                               7.0         1
                Transporter    NaN        18
                               5.0        11
                Van            NaN         2
Renault Duster  Off-Road       6.0        25
                               NaN         9
Renault Espace  Compact        NaN         3
                               6.0         2
                               7.0         1
                Coupe          NaN         2
                Off-Road       6.0         4
                               5.0         2
                               NaN         2
                Other          6.0         4
                               NaN         3
                               7.0         1
                Sedans         NaN        15
                               6.0         3
                               7.0         3
                Station wagon  6.0        60
                               7.0        22
                               NaN         9
                Transporter    6.0        47
                               7.0         3
                               NaN         2
                Van            6.0       359
                               NaN       329
                               7.0       105
                               9.0         6
                               3.0         2
                               4.0         2
Name: count, dtype: int64

In [90]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'gears', 'mode')
df['gears'] = df_tmp['gears']

#### Column: cylinders

In [91]:
df['cylinders'].value_counts(dropna=False)

cylinders
4.0    8105
NaN    5680
3.0    2104
5.0      22
6.0       3
8.0       2
2.0       2
1.0       1
Name: count, dtype: int64

In [92]:
df.groupby(['make_model', 'body_type'])['cylinders'].value_counts(dropna=False)

make_model      body_type      cylinders
Audi A1         Compact        NaN           477
                               3.0           451
                               4.0           110
                               8.0             1
                Coupe          3.0             1
                               NaN             1
                Other          NaN             6
                               3.0             4
                               4.0             3
                Sedans         3.0           892
                               NaN           369
                               4.0           277
                Station wagon  3.0            10
                               4.0             6
                               NaN             5
                Van            NaN             1
Audi A2         Off-Road       NaN             1
Audi A3         Compact        4.0           136
                               NaN            28
                               3.0            17
                               5.0             1
                Convertible    4.0             8
                Coupe          4.0             3
                               3.0             1
                Other          NaN             9
                               4.0             6
                               3.0             1
                Sedans         4.0          1647
                               NaN           634
                               3.0           306
                               5.0            18
                Station wagon  NaN           132
                               4.0           100
                               3.0            48
                               5.0             2
Opel Astra      Compact        4.0           102
                               NaN            62
                               3.0            21
                Coupe          4.0             1
                               NaN             1
                Off-Road       4.0             1
                Other          4.0            50
                               NaN            12
                               3.0             5
                Sedans         NaN           520
                               4.0           421
                               3.0           112
                Station wagon  4.0           669
                               NaN           511
                               3.0            38
Opel Corsa      Compact        4.0           622
                               NaN           606
                               3.0             3
                               1.0             1
                Coupe          4.0            10
                               NaN             2
                               3.0             1
                Off-Road       4.0             3
                Other          4.0            79
                               NaN             7
                               3.0             1
                Sedans         4.0           671
                               NaN           201
                               3.0             3
                Transporter    4.0             6
                               3.0             1
                Van            NaN             2
Opel Insignia   Compact        4.0            22
                               NaN             5
                Coupe          NaN             1
                Off-Road       4.0             6
                               NaN             1
                Other          4.0            46
                               NaN             2
                Sedans         4.0           586
                               NaN           313
                               6.0             1
                Station wagon  4.0           968
                               NaN           643
                               6.0             2
                               2.0             1
                Van            4.0             1
Renault Clio    Compact        NaN           274
                               4.0           161
                               3.0            49
                Coupe          4.0             1
                Off-Road       4.0             2
                Other          NaN            45
                               4.0             5
                               3.0             1
                Sedans         4.0           514
                               NaN           293
                               3.0           125
                               5.0             1
                Station wagon  4.0           180
                               NaN           146
                               3.0            11
                Transporter    NaN            19
                               4.0             8
                               3.0             2
                Van            4.0             1
                               NaN             1
Renault Duster  Off-Road       4.0            33
                               NaN             1
Renault Espace  Compact        NaN             5
                               4.0             1
                Coupe          NaN             2
                Off-Road       4.0             4
                               NaN             4
                Other          4.0             5
                               NaN             3
                Sedans         4.0            12
                               NaN             9
                Station wagon  4.0            78
                               NaN            13
                Transporter    4.0            50
                               NaN             2
                Van            4.0           490
                               NaN           311
                               2.0             1
                               8.0             1
Name: count, dtype: int64

In [93]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'cylinders', 'mode')
df['cylinders'] = df_tmp['cylinders']

#### Column: hp

In [94]:
df['hp'].isnull().groupby([df['make_model'], df['body_type']]).sum()

make_model      body_type
Audi A1         Compact           2
                Coupe             0
                Other             0
                Sedans            0
                Station wagon     0
                Van               0
Audi A2         Off-Road          0
Audi A3         Compact           1
                Convertible       0
                Coupe             0
                Other             0
                Sedans            0
                Station wagon     0
Opel Astra      Compact           1
                Coupe             0
                Off-Road          0
                Other             0
                Sedans            1
                Station wagon     0
Opel Corsa      Compact           1
                Coupe             0
                Off-Road          0
                Other             0
                Sedans            1
                Transporter       0
                Van               0
Opel Insignia   Compact           0
                Coupe             0
                Off-Road          0
                Other             1
                Sedans            6
                Station wagon     3
                Van               0
Renault Clio    Compact           8
                Coupe             0
                Off-Road          0
                Other             0
                Sedans           20
                Station wagon     1
                Transporter       0
                Van               0
Renault Duster  Off-Road          8
Renault Espace  Compact           0
                Coupe             0
                Off-Road          0
                Other             1
                Sedans            0
                Station wagon     0
                Transporter       0
                Van              33
Name: hp, dtype: int64

In [95]:
df['hp'].describe()

count    15831.000000
mean        88.367696
std         26.835135
min          1.000000
25%         66.000000
50%         85.000000
75%        101.000000
max        294.000000
Name: hp, dtype: float64

In [96]:
df.groupby(['make_model', 'body_type'])['hp'].median()

make_model      body_type
Audi A1         Compact           70.0
                Coupe             77.5
                Other             70.0
                Sedans            70.0
                Station wagon     70.0
                Van              147.0
Audi A2         Off-Road          85.0
Audi A3         Compact           85.0
                Convertible      110.0
                Coupe             81.0
                Other             85.0
                Sedans            85.0
                Station wagon     85.0
Opel Astra      Compact           81.0
                Coupe            106.5
                Off-Road         110.0
                Other             81.0
                Sedans            81.0
                Station wagon    100.0
Opel Corsa      Compact           66.0
                Coupe             55.0
                Off-Road          66.0
                Other             66.0
                Sedans            55.0
                Transporter       55.0
                Van               51.0
Opel Insignia   Compact          121.0
                Coupe             81.0
                Off-Road         125.0
                Other            100.0
                Sedans           103.0
                Station wagon    121.0
                Van              121.0
Renault Clio    Compact           56.0
                Coupe            147.0
                Off-Road          71.0
                Other             56.0
                Sedans            56.0
                Station wagon     66.0
                Transporter       56.0
                Van               55.0
Renault Duster  Off-Road          77.0
Renault Espace  Compact          133.0
                Coupe            141.5
                Off-Road         118.0
                Other            118.0
                Sedans           118.0
                Station wagon    118.0
                Transporter      118.0
                Van              118.0
Name: hp, dtype: float64

In [97]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'hp', 'median')
df['hp'] = df_tmp['hp']

#### Column: displacement

In [98]:
df['displacement'].isnull().groupby([df['make_model'], df['body_type']]).sum()

make_model      body_type
Audi A1         Compact          12
                Coupe             0
                Other             1
                Sedans           15
                Station wagon     1
                Van               0
Audi A2         Off-Road          0
Audi A3         Compact           2
                Convertible       0
                Coupe             0
                Other             3
                Sedans           38
                Station wagon     7
Opel Astra      Compact          30
                Coupe             0
                Off-Road          0
                Other             0
                Sedans           19
                Station wagon    40
Opel Corsa      Compact          20
                Coupe             1
                Off-Road          0
                Other             0
                Sedans           53
                Transporter       0
                Van               0
Opel Insignia   Compact           0
                Coupe             1
                Off-Road          0
                Other             0
                Sedans           41
                Station wagon    33
                Van               0
Renault Clio    Compact          19
                Coupe             0
                Off-Road          0
                Other             0
                Sedans           56
                Station wagon    15
                Transporter       1
                Van               0
Renault Duster  Off-Road          1
Renault Espace  Compact           2
                Coupe             2
                Off-Road          0
                Other             1
                Sedans            0
                Station wagon     4
                Transporter       2
                Van              76
Name: displacement, dtype: int64

In [99]:
df['displacement'].describe()

count    15423.000000
mean      1423.540881
std        333.530658
min          1.000000
25%       1229.000000
50%       1461.000000
75%       1598.000000
max      16000.000000
Name: displacement, dtype: float64

In [100]:
df.groupby(['make_model', 'body_type'])['displacement'].median()

make_model      body_type
Audi A1         Compact           999.0
                Coupe            1298.5
                Other             999.0
                Sedans            999.0
                Station wagon    1395.0
                Van              1984.0
Audi A2         Off-Road         1598.0
Audi A3         Compact          1598.0
                Convertible      1968.0
                Coupe            1598.0
                Other            1598.0
                Sedans           1598.0
                Station wagon    1598.0
Opel Astra      Compact          1598.0
                Coupe            1381.5
                Off-Road         1399.0
                Other            1399.0
                Sedans           1399.0
                Station wagon    1598.0
Opel Corsa      Compact          1398.0
                Coupe            1238.5
                Off-Road         1400.0
                Other            1398.0
                Sedans           1357.0
                Transporter      1248.0
                Van              1229.0
Opel Insignia   Compact          1598.0
                Coupe               NaN
                Off-Road         1956.0
                Other            1598.0
                Sedans           1598.0
                Station wagon    1598.0
                Van              1496.0
Renault Clio    Compact          1197.0
                Coupe            1618.0
                Off-Road         1329.0
                Other            1197.0
                Sedans           1461.0
                Station wagon    1197.0
                Transporter      1461.0
                Van              1461.0
Renault Duster  Off-Road         1598.0
Renault Espace  Compact          1608.0
                Coupe               NaN
                Off-Road         1598.0
                Other            1598.0
                Sedans           1598.0
                Station wagon    1598.0
                Transporter      1598.0
                Van              1598.0
Name: displacement, dtype: float64

In [101]:
df_tmp = fill_two_stage(df, 'make_model', 'body_type', 'displacement', 'median')
df['displacement'] = df_tmp['displacement']

#### Column: fuel

In [102]:
df['fuel'].value_counts(dropna=False)

fuel
Gasoline    8545
Diesel      7299
Gaseous       64
Others         6
Electric       5
Name: count, dtype: int64

#### Column: co2_emission

In [103]:
df['co2_emission'].isnull().groupby([df['fuel'], df['age']]).sum()

fuel      age
Diesel    0.0    205
          1.0    265
          2.0    353
          3.0    509
Electric  1.0      0
          3.0      2
Gaseous   0.0      2
          1.0      0
          2.0      6
          3.0      5
Gasoline  0.0    464
          1.0    300
          2.0    188
          3.0    133
Others    0.0      0
          1.0      1
          2.0      1
          3.0      2
Name: co2_emission, dtype: int64

In [104]:
df['co2_emission'].describe()

count    13483.000000
mean       117.953942
std         20.245589
min          0.000000
25%        104.000000
50%        116.000000
75%        129.000000
max        990.000000
Name: co2_emission, dtype: float64

In [105]:
df.groupby(['fuel', 'age'])['co2_emission'].median()

fuel      age
Diesel    0.0    118.0
          1.0    107.0
          2.0    105.0
          3.0    104.0
Electric  1.0     36.0
          3.0      NaN
Gaseous   0.0     98.0
          1.0    105.5
          2.0     91.0
          3.0     94.0
Gasoline  0.0    124.0
          1.0    124.0
          2.0    120.0
          3.0    120.0
Others    0.0    126.0
          1.0    108.0
          2.0      NaN
          3.0      NaN
Name: co2_emission, dtype: float64

In [106]:
df_tmp = fill_two_stage(df, 'fuel', 'age', 'co2_emission', 'median')
df['co2_emission'] = df_tmp['co2_emission']

#### Column: emission_class

In [107]:
df['emission_class'].value_counts(dropna=False)

emission_class
Euro 6    12173
NaN        3628
Euro 5       78
Euro 4       40
Name: count, dtype: int64

In [108]:
df.groupby(['fuel', 'age'])['emission_class'].value_counts(dropna=False)

fuel      age  emission_class
Diesel    0.0  Euro 6             589
               NaN                326
          1.0  Euro 6            1584
               NaN                307
               Euro 5               2
          2.0  Euro 6            1561
               NaN                380
               Euro 5               7
          3.0  Euro 6            1991
               NaN                510
               Euro 5              40
               Euro 4               2
Electric  1.0  Euro 6               3
          3.0  Euro 6               1
               NaN                  1
Gaseous   0.0  Euro 6              16
               NaN                  3
          1.0  Euro 6               4
          2.0  Euro 6              11
               NaN                  6
          3.0  Euro 6              18
               NaN                  5
               Euro 5               1
Gasoline  0.0  Euro 6            2423
               NaN               1019
               Euro 4              33
               Euro 5               1
          1.0  Euro 6            2045
               NaN                569
               Euro 5               6
               Euro 4               3
          2.0  Euro 6            1039
               NaN                258
               Euro 5               9
               Euro 4               1
          3.0  Euro 6             885
               NaN                241
               Euro 5              12
               Euro 4               1
Others    0.0  Euro 6               1
          1.0  Euro 6               1
               NaN                  1
          2.0  NaN                  1
          3.0  Euro 6               1
               NaN                  1
Name: count, dtype: int64

In [109]:
df_tmp = fill_two_stage(df, 'fuel', 'age', 'emission_class', 'mode')
df['emission_class'] = df_tmp['emission_class']

#### Column: emission_label

In [110]:
df['emission_label'].value_counts(dropna=False)

emission_label
NaN    11974
4.0     3553
1.0      381
5.0        8
3.0        2
2.0        1
Name: count, dtype: int64

In [111]:
df.groupby(['fuel', 'age'])['emission_label'].value_counts(dropna=False)

fuel      age  emission_label
Diesel    0.0  NaN                633
               4.0                210
               1.0                 71
               3.0                  1
          1.0  NaN               1614
               4.0                203
               1.0                 75
               5.0                  1
          2.0  NaN               1702
               4.0                208
               1.0                 38
          3.0  NaN               2096
               4.0                412
               1.0                 35
Electric  1.0  NaN                  3
          3.0  NaN                  2
Gaseous   0.0  NaN                 18
               1.0                  1
          1.0  NaN                  4
          2.0  NaN                 15
               4.0                  2
          3.0  NaN                 23
               4.0                  1
Gasoline  0.0  NaN               2203
               4.0               1159
               1.0                113
               2.0                  1
          1.0  NaN               1829
               4.0                766
               1.0                 23
               5.0                  4
               3.0                  1
          2.0  NaN                954
               4.0                337
               1.0                 14
               5.0                  2
          3.0  NaN                875
               4.0                252
               1.0                 11
               5.0                  1
Others    0.0  NaN                  1
          1.0  4.0                  1
               NaN                  1
          2.0  4.0                  1
          3.0  4.0                  1
               NaN                  1
Name: count, dtype: int64

In [112]:
df_tmp = fill_two_stage(df, 'fuel', 'age', 'emission_label', 'mode')
df['emission_label'] = df_tmp['emission_label']

#### Column: consumption_comb

In [113]:
df['consumption_comb'].isnull().groupby([df['make_model'], df['fuel']]).sum()

make_model      fuel
Audi A1         Diesel       53
                Gasoline    131
                Others        1
Audi A2         Diesel        0
Audi A3         Diesel      246
                Electric      1
                Gaseous       6
                Gasoline     89
                Others        2
Opel Astra      Diesel      171
                Gaseous       1
                Gasoline    212
Opel Corsa      Diesel       57
                Gaseous       9
                Gasoline    181
                Others        0
Opel Insignia   Diesel      334
                Gasoline     76
                Others        1
Renault Clio    Diesel      158
                Electric      1
                Gaseous       7
                Gasoline    116
                Others        0
Renault Duster  Gasoline      1
Renault Espace  Diesel      158
                Gasoline     21
Name: consumption_comb, dtype: int64

In [114]:
df['consumption_comb'].describe()

count    13886.000000
mean         4.895549
std          1.635382
min          0.000000
25%          4.100000
50%          4.800000
75%          5.500000
max         55.000000
Name: consumption_comb, dtype: float64

In [115]:
df.groupby(['make_model', 'fuel'])['consumption_comb'].median()

make_model      fuel
Audi A1         Diesel       3.80
                Gasoline     4.60
                Others        NaN
Audi A2         Diesel       4.90
Audi A3         Diesel       4.00
                Electric     1.60
                Gaseous      3.40
                Gasoline     5.10
                Others        NaN
Opel Astra      Diesel       3.70
                Gaseous      3.60
                Gasoline     5.40
Opel Corsa      Diesel       3.80
                Gaseous      5.45
                Gasoline     5.40
                Others       5.10
Opel Insignia   Diesel       5.10
                Gasoline     6.10
                Others        NaN
Renault Clio    Diesel       3.30
                Electric      NaN
                Gaseous      6.10
                Gasoline     5.40
                Others       4.70
Renault Duster  Gasoline    10.00
Renault Espace  Diesel       4.70
                Gasoline     6.80
Name: consumption_comb, dtype: float64

In [116]:
df_tmp = fill_two_stage(df, 'make_model', 'fuel', 'consumption_comb', 'median')
df['consumption_comb'] = df_tmp['consumption_comb']

#### Column: consumption_city

In [117]:
df['consumption_city'].isnull().groupby([df['make_model'], df['fuel']]).sum()

make_model      fuel
Audi A1         Diesel       61
                Gasoline    211
                Others        1
Audi A2         Diesel        0
Audi A3         Diesel      211
                Electric      4
                Gaseous       6
                Gasoline    128
                Others        2
Opel Astra      Diesel      193
                Gaseous       1
                Gasoline    238
Opel Corsa      Diesel       63
                Gaseous       9
                Gasoline    247
                Others        0
Opel Insignia   Diesel      372
                Gasoline     93
                Others        1
Renault Clio    Diesel      181
                Electric      1
                Gaseous       7
                Gasoline    157
                Others        0
Renault Duster  Gasoline     17
Renault Espace  Diesel      200
                Gasoline     32
Name: consumption_city, dtype: int64

In [118]:
df['consumption_city'].describe()

count    13483.000000
mean         5.947801
std          1.966939
min          0.000000
25%          4.700000
50%          5.800000
75%          7.000000
max         66.000000
Name: consumption_city, dtype: float64

In [119]:
df.groupby(['make_model', 'fuel'])['consumption_city'].median()

make_model      fuel
Audi A1         Diesel       4.40
                Gasoline     5.80
                Others        NaN
Audi A2         Diesel       5.60
Audi A3         Diesel       4.50
                Electric      NaN
                Gaseous      4.30
                Gasoline     5.90
                Others        NaN
Opel Astra      Diesel       4.20
                Gaseous      4.40
                Gasoline     7.10
Opel Corsa      Diesel       4.60
                Gaseous      6.85
                Gasoline     6.90
                Others       6.50
Opel Insignia   Diesel       6.50
                Gasoline     7.60
                Others        NaN
Renault Clio    Diesel       3.50
                Electric      NaN
                Gaseous      7.80
                Gasoline     6.80
                Others       5.70
Renault Duster  Gasoline    10.00
Renault Espace  Diesel       5.10
                Gasoline     8.70
Name: consumption_city, dtype: float64

In [120]:
df_tmp = fill_two_stage(df, 'make_model', 'fuel', 'consumption_city', 'median')
df['consumption_city'] = df_tmp['consumption_city']

#### Column: consumption_country

In [121]:
df['consumption_country'].isnull().groupby([df['make_model'], df['fuel']]).sum()

make_model      fuel
Audi A1         Diesel       59
                Gasoline    210
                Others        1
Audi A2         Diesel        0
Audi A3         Diesel      207
                Electric      4
                Gaseous       6
                Gasoline    119
                Others        2
Opel Astra      Diesel      188
                Gaseous       1
                Gasoline    237
Opel Corsa      Diesel       62
                Gaseous       1
                Gasoline    236
                Others        0
Opel Insignia   Diesel      367
                Gasoline     94
                Others        1
Renault Clio    Diesel      180
                Electric      1
                Gaseous       3
                Gasoline    157
                Others        0
Renault Duster  Gasoline      1
Renault Espace  Diesel      201
                Gasoline     38
Name: consumption_country, dtype: int64

In [122]:
df['consumption_country'].describe()

count    13543.000000
mean         4.238404
std          1.194201
min          0.000000
25%          3.700000
50%          4.200000
75%          4.600000
max         44.000000
Name: consumption_country, dtype: float64

In [123]:
df.groupby(['make_model', 'fuel'])['consumption_country'].median()

make_model      fuel
Audi A1         Diesel       3.4
                Gasoline     3.9
                Others       NaN
Audi A2         Diesel       4.5
Audi A3         Diesel       3.7
                Electric     NaN
                Gaseous      2.9
                Gasoline     4.3
                Others       NaN
Opel Astra      Diesel       3.5
                Gaseous      3.0
                Gasoline     4.4
Opel Corsa      Diesel       3.3
                Gaseous      5.7
                Gasoline     4.6
                Others       4.3
Opel Insignia   Diesel       4.2
                Gasoline     5.2
                Others       NaN
Renault Clio    Diesel       3.1
                Electric     NaN
                Gaseous      5.1
                Gasoline     4.5
                Others       4.1
Renault Duster  Gasoline    10.0
Renault Espace  Diesel       4.4
                Gasoline     5.7
Name: consumption_country, dtype: float64

In [124]:
df_tmp = fill_two_stage(df, 'make_model', 'fuel', 'consumption_country', 'median')
df['consumption_country'] = df_tmp['consumption_country']

#### Column: price

In [125]:
df['price'].describe()

count    15919.000000
mean     18019.896727
std       7386.169409
min         13.000000
25%      12850.000000
50%      16900.000000
75%      21900.000000
max      74600.000000
Name: price, dtype: float64

### Dataset export

In [126]:
df.head()

,make_model,body_type,vat,registration_year,prev_owner,type,inspection_new,body_color,paint_type,upholstery_texture,upholstery_color,gearing_type,fuel,co2_emission,emission_class,emission_label,drive_chain,consumption_comb,consumption_city,consumption_country,country_version,entertainment_media,safety_security,comfort_convenience,extras,price,km,hp,displacement,warranty,weight,nr_of_doors,nr_of_seats,cylinders,gears,age
0,Audi A1,Sedans,VAT deductible,2016.0,2.0,Used,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.3,3.5,Germany,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Catalytic Converter,Voice Control",15770,56013.0,66.0,1422.0,0.0,1220.0,5.0,5.0,3.0,5.0,3.0
1,Audi A1,Sedans,Price negotiable,2017.0,1.0,Used,No,Red,Metallic,Cloth,Grey,Automatic,Gasoline,129.0,Euro 6,4.0,Front,5.6,7.1,4.7,Germany,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Central door lock with r...","Air conditioning,Automatic climate control,Hil...","Alloy wheels,Sport seats,Sport suspension,Voic...",14500,80000.0,141.0,1798.0,0.0,1255.0,3.0,4.0,4.0,7.0,2.0
2,Audi A1,Sedans,VAT deductible,2016.0,1.0,Used,No,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.4,3.4,Germany,"MP3,On-board computer","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Cruise control,Electrical sid...","Alloy wheels,Voice Control",14640,83450.0,85.0,1598.0,0.0,1195.0,4.0,4.0,3.0,5.0,3.0
3,Audi A1,Sedans,Missing,2016.0,1.0,Used,No,Brown,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.3,3.5,Germany,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Alarm system,Central door lock with remote...","Air suspension,Armrest,Auxiliary heating,Elect...","Alloy wheels,Sport seats,Voice Control",14500,73000.0,66.0,1422.0,0.0,1195.0,3.0,4.0,3.0,6.0,3.0
4,Audi A1,Sedans,Missing,2016.0,1.0,Used,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,109.0,Euro 6,4.0,Front,4.1,4.6,3.8,Germany,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Central door lock,Driver-side airbag,Elect...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Sport package,Sport suspension,Vo...",16790,16200.0,66.0,1422.0,0.0,1195.0,5.0,5.0,3.0,5.0,3.0

In [127]:
df.isnull().sum()*100 / df.shape[0]

make_model             0.0
body_type              0.0
vat                    0.0
registration_year      0.0
prev_owner             0.0
type                   0.0
inspection_new         0.0
body_color             0.0
paint_type             0.0
upholstery_texture     0.0
upholstery_color       0.0
gearing_type           0.0
fuel                   0.0
co2_emission           0.0
emission_class         0.0
emission_label         0.0
drive_chain            0.0
consumption_comb       0.0
consumption_city       0.0
consumption_country    0.0
country_version        0.0
entertainment_media    0.0
safety_security        0.0
comfort_convenience    0.0
extras                 0.0
price                  0.0
km                     0.0
hp                     0.0
displacement           0.0
warranty               0.0
weight                 0.0
nr_of_doors            0.0
nr_of_seats            0.0
cylinders              0.0
gears                  0.0
age                    0.0
dtype: float64

In [128]:
df.drop('registration_year', axis=1, inplace=True)

In [129]:
df.head()

,make_model,body_type,vat,prev_owner,type,inspection_new,body_color,paint_type,upholstery_texture,upholstery_color,gearing_type,fuel,co2_emission,emission_class,emission_label,drive_chain,consumption_comb,consumption_city,consumption_country,country_version,entertainment_media,safety_security,comfort_convenience,extras,price,km,hp,displacement,warranty,weight,nr_of_doors,nr_of_seats,cylinders,gears,age
0,Audi A1,Sedans,VAT deductible,2.0,Used,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.3,3.5,Germany,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Catalytic Converter,Voice Control",15770,56013.0,66.0,1422.0,0.0,1220.0,5.0,5.0,3.0,5.0,3.0
1,Audi A1,Sedans,Price negotiable,1.0,Used,No,Red,Metallic,Cloth,Grey,Automatic,Gasoline,129.0,Euro 6,4.0,Front,5.6,7.1,4.7,Germany,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Central door lock with r...","Air conditioning,Automatic climate control,Hil...","Alloy wheels,Sport seats,Sport suspension,Voic...",14500,80000.0,141.0,1798.0,0.0,1255.0,3.0,4.0,4.0,7.0,2.0
2,Audi A1,Sedans,VAT deductible,1.0,Used,No,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.4,3.4,Germany,"MP3,On-board computer","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Cruise control,Electrical sid...","Alloy wheels,Voice Control",14640,83450.0,85.0,1598.0,0.0,1195.0,4.0,4.0,3.0,5.0,3.0
3,Audi A1,Sedans,Missing,1.0,Used,No,Brown,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.3,3.5,Germany,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Alarm system,Central door lock with remote...","Air suspension,Armrest,Auxiliary heating,Elect...","Alloy wheels,Sport seats,Voice Control",14500,73000.0,66.0,1422.0,0.0,1195.0,3.0,4.0,3.0,6.0,3.0
4,Audi A1,Sedans,Missing,1.0,Used,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,109.0,Euro 6,4.0,Front,4.1,4.6,3.8,Germany,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Central door lock,Driver-side airbag,Elect...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Sport package,Sport suspension,Vo...",16790,16200.0,66.0,1422.0,0.0,1195.0,5.0,5.0,3.0,5.0,3.0

In [130]:
df.shape

(15919, 35)

In [131]:
df.columns

Index(['make_model', 'body_type', 'vat', 'prev_owner', 'type',
       'inspection_new', 'body_color', 'paint_type', 'upholstery_texture',
       'upholstery_color', 'gearing_type', 'fuel', 'co2_emission',
       'emission_class', 'emission_label', 'drive_chain', 'consumption_comb',
       'consumption_city', 'consumption_country', 'country_version',
       'entertainment_media', 'safety_security', 'comfort_convenience',
       'extras', 'price', 'km', 'hp', 'displacement', 'warranty', 'weight',
       'nr_of_doors', 'nr_of_seats', 'cylinders', 'gears', 'age'],
      dtype='object')

In [132]:
df.to_csv(drive_data_dir+'/data_fill.csv', index=False)